// Sample product data with images, prices, and descriptions

    const products = [
        { id: 1, name: 'Manter Pickled Lettuce', category: 'pickled_fermented_foods', price: 3.99, description: 'Per unit', image: 'cannedimages/Manter Pickled Lettuce.png' },
        { id: 2, name: 'Kimlan Sweet Sauce', category: 'sauces_pastes', price: 4.99, description: 'Per unit', image: 'cannedimages/Kimlan Sweet Sauce.png' },
        { id: 3, name: 'Kavista Preserved Bean Curd', category: 'pickled_fermented_foods', price: 2.99, description: 'Per unit', image: 'cannedimages/Kavista Preserved Bean Curd.png' },
        { id: 4, name: 'Kabuto Red Bean Paste', category: 'sweets_desserts', price: 3.59, description: 'Per unit', image: 'cannedimages/Kabuto Red Bean Paste.png' },
        { id: 5, name: 'Akebono Sweetened Red Bean', category: 'sweets_desserts', price: 3.99, description: 'Per unit', image: 'cannedimages/Akebono Sweetened Red Bean.png' },
        { id: 6, name: 'Surasang Red Bean Paste', category: 'sweets_desserts', price: 4.99, description: 'Per unit', image: 'cannedimages/Surasang Red Bean Paste.png' },
        { id: 7, name: 'Kimbo Pickled Lettuce in Soy Sauce', category: 'pickled_fermented_foods', price: 2.99, description: 'Per unit', image: 'cannedimages/Kimbo Pickled Lettuce in Soy Sauce.png' },
        { id: 8, name: 'Morinaga Red Bean Paste', category: 'sweets_desserts', price: 5.99, description: 'Per unit', image: 'cannedimages/Morinaga Red Bean Paste.png' },
        { id: 9, name: 'Kabuto Koshian Red Bean Paste', category: 'sweets_desserts', price: 3.59, description: 'Per unit', image: 'cannedimages/Kabuto Koshian Red Bean Paste.png' },
        { id: 10, name: 'Preserved Pickled Mustard FSG', category: 'pickled_fermented_foods', price: 3.99, description: 'Per unit', image: 'cannedimages/Preserved Pickled Mustard FSG.png' },
        { id: 11, name: 'Crisp Black Fungus FSG', category: 'vegetables', price: 3.99, description: 'Per unit', image: 'cannedimages/Crisp Black Fungus FSG.png' },
        { id: 12, name: 'Preserved Cabbage FSG', category: 'pickled_fermented_foods', price: 3.99, description: 'Per unit', image: 'cannedimages/Preserved Cabbage FSG.png' },
        { id: 13, name: 'JB Red Bean Paste', category: 'sweets_desserts', price: 3.99, description: 'Per unit', image: 'cannedimages/JB Red Bean Paste.png' },
        { id: 14, name: 'JB Tsubuan Coarse Red Bean Paste', category: 'sweets_desserts', price: 3.99, description: 'Per unit', image: 'cannedimages/JB Tsubuan Coarse Red Bean Paste.png' },
        { id: 15, name: 'Tiffany Mustard Green Sour', category: 'pickled_fermented_foods', price: 3.59, description: 'Per unit', image: 'cannedimages/Tiffany Mustard Green Sour.png' },
        { id: 16, name: 'Tianjin Preserved Vegetable Great Wall', category: 'vegetables', price: 5.99, description: 'Per unit', image: 'cannedimages/Tianjin Preserved Vegetable Great Wall.png' },
        { id: 17, name: 'Havista Soy Bean Sauce', category: 'sauces_pastes', price: 5.99, description: 'Per unit', image: 'cannedimages/Havista Soy Bean Sauce.png' },
        { id: 18, name: 'Yefend Bamboo Shoot', category: 'vegetables', price: 2.99, description: 'Per unit', image: 'cannedimages/Yefend Bamboo Shoot.png' },
        { id: 19, name: 'Saline Bamboo Shoots', category: 'vegetables', price: 2.99, description: 'Per unit', image: 'cannedimages/Saline Bamboo Shoots.png' },
        { id: 20, name: 'LSK Saline Bamboo Shoots', category: 'vegetables', price: 2.99, description: 'Per unit', image: 'cannedimages/LSK Saline Bamboo Shoots.png' },
        { id: 21, name: 'Red Havista Preserved Bean Curd', category: 'pickled_fermented_foods', price: 2.99, description: 'Per unit', image: 'cannedimages/Red Havista Preserved Bean Curd.png' },
        { id: 22, name: 'Red Fermented Rice Sauce', category: 'sauces_pastes', price: 9.99, description: 'Per unit', image: 'cannedimages/Red Fermented Rice Sauce.png' },
        { id: 23, name: 'Fermented Tofu Paste', category: 'pickled_fermented_foods', price: 5.99, description: 'Per unit', image: 'cannedimages/Fermented Tofu Paste.png' },
        { id: 24, name: 'Wei-Chuan Pickled Cucumber In Soy Sauce', category: 'pickled_fermented_foods', price: 3.99, description: 'Per unit', image: 'cannedimages/Wei-Chuan Pickled Cucumber In Soy Sauce.png' },
        { id: 25, name: 'Wei-Chuan Fried Gluten In Soy Sauce', category: 'pickled_fermented_foods', price: 1.99, description: 'Per unit', image: 'cannedimages/Wei-Chuan Fried Gluten In Soy Sauce.png' },
        
        { id: 26, name: 'Wei-Chuan Fried Gluten w/Peanut In Soy Sauce', category: 'pickled_fermented_foods', price: 1.99, description: 'Per unit', image: 'cannedimages/Wei-Chuan Fried Gluten with Peanut In Soy Sauce.png' },
{ id: 27, name: 'Braised Abalone', category: 'seafood', price: 9.99, description: 'Per unit', image: 'cannedimages/Braised Abalone.png' },
{ id: 28, name: 'Ox & Palm Corned Beef Chunky', category: 'meat_poultry', price: 8.99, description: 'Per unit', image: 'cannedimages/Ox & Palm Corned Beef Chunky.png' },
{ id: 29, name: 'Ox & Palm Corned Beef Onion', category: 'meat_poultry', price: 7.99, description: 'Per unit', image: 'cannedimages/Ox & Palm Corned Beef Onion.png' },
{ id: 30, name: 'Argentina Corned Beef', category: 'meat_poultry', price: 7.99, description: 'Per unit', image: 'cannedimages/Argentina Corned Beef.png' },
{ id: 31, name: 'KH Crown Corned Beef', category: 'meat_poultry', price: 11.99, description: 'Per unit', image: 'cannedimages/KH Crown Corned Beef.png' },
{ id: 32, name: 'Argentina Chunky Corned Beef', category: 'meat_poultry', price: 7.99, description: 'Per unit', image: 'cannedimages/Argentina Chunky Corned Beef.png' },
{ id: 33, name: 'Dongwon Fiery Hot Tuna', category: 'seafood', price: 3.50, description: 'Per unit', image: 'cannedimages/Dongwon Fiery Hot Tuna.png' },
{ id: 34, name: 'Century Japanese Mackerel In Brine', category: 'seafood', price: 3.99, description: 'Per unit', image: 'cannedimages/Century Japanese Mackerel In Brine.png' },
{ id: 35, name: 'Century Japanese Mackerel In Shoyu', category: 'seafood', price: 3.99, description: 'Per unit', image: 'cannedimages/Century Japanese Mackerel In Shoyu.png' },
{ id: 36, name: 'Century Japanese Mackerel In Miso', category: 'seafood', price: 3.99, description: 'Per unit', image: 'cannedimages/Century Japanese Mackerel In Miso.png' },
{ id: 37, name: 'Century Tuna Flakes With Calamansi', category: 'seafood', price: 2.99, description: 'Per unit', image: 'cannedimages/Century Tuna Flakes With Calamansi.png' },
{ id: 38, name: 'Century Afritada Style Tuna In Tomato Sauce and Vegetables', category: 'seafood', price: 2.99, description: 'Per unit', image: 'cannedimages/Century Afritada Style Tuna In Tomato Sauce and Vegetables.png' },
{ id: 39, name: 'Century Caldereta Style Tuna In Spanish Style Tomato Sauce', category: 'seafood', price: 2.99, description: 'Per unit', image: 'cannedimages/Century Caldereta Style Tuna In Spanish Style Tomato Sauce.png' },
{ id: 40, name: 'Century Tuna Flakes in Brine', category: 'seafood', price: 2.99, description: 'Per unit', image: 'cannedimages/Century Tuna Flakes in Brine.png' },
{ id: 41, name: 'Century Chili Corned Tuna', category: 'seafood', price: 2.99, description: 'Per unit', image: 'cannedimages/Century Chili Corned Tuna.png' },
{ id: 42, name: 'Century Milkfish Fillet Spanish Style', category: 'seafood', price: 2.99, description: 'Per unit', image: 'cannedimages/Century Milkfish Fillet Spanish Style.png' },
{ id: 43, name: 'Century Adobo Style Tuna in Soy Sauce', category: 'seafood', price: 2.99, description: 'Per unit', image: 'cannedimages/Century Adobo Style Tuna in Soy Sauce.png' },
{ id: 44, name: 'Century Mechado Style Tuna in Filipinos', category: 'seafood', price: 2.99, description: 'Per unit', image: 'cannedimages/Century Mechado Style Tuna in Filipinos.png' },
{ id: 45, name: 'Imperial Taste Sardines in Tomato Sauce', category: 'seafood', price: 2.99, description: 'Per unit', image: 'cannedimages/Imperial Taste Sardines in Tomato Sauce.png' },
{ id: 46, name: 'Kuromane Amani - Beans', category: 'legumes_beans', price: 2.99, description: 'Per unit', image: 'cannedimages/KuromaneAmaniBeans.png'},
{ id: 47, name: 'Dongwon Bai Top Shell Meat', category: 'seafood', price: 9.99, description: 'Per unit', image: 'cannedimages/Dongwon Bai Top Shell Meat.png' },
{ id: 48, name: 'Dongwon Baitop Shell Hot', category: 'seafood', price: 9.99, description: 'Per unit', image: 'cannedimages/Dongwon Baitop Shell Hot.png' },
{ id: 49, name: '555 Gourmet Tuyo Dried Herring', category: 'seafood', price: 5.99, description: 'Per unit', image: 'cannedimages/555 Gourmet Tuyo Dried Herring.png' },
{ id: 50, name: '555 Spanish Sardines in Extra Spicy Corn Oil', category: 'seafood', price: 2.98, description: 'Per unit', image: 'cannedimages/555 Spanish Sardines in Extra Spicy Corn Oil.png' },

{ id: 51, name: 'San Sebastian Dried Herring with Garlic in Olive Oil', category: 'seafood', price: 4.99, description: 'Per unit', image: 'cannedimages/San Sebastian Dried Herring with Garlic in Olive Oil.png' },
{ id: 52, name: 'Top Ajitsuki IWashi', category: 'seafood', price: 1.99, description: 'Per unit', image: 'cannedimages/Top Ajitsuki IWashi.png' },
{ id: 53, name: 'SF Crispy Baby Clam', category: 'seafood', price: 1.99, description: 'Per unit', image: 'cannedimages/SF Crispy Baby Clam.png' },
{ id: 54, name: 'Minced Prawn in Spices Lee', category: 'seafood', price: 2.29, description: 'Per unit', image: 'cannedimages/Minced Prawn in Spices Lee.png' },
{ id: 55, name: 'Gia Vi Nau Bun Rieu Lal Mince Prawn in Spices', category: 'seafood', price: 1.99, description: 'Per unit', image: 'cannedimages/Gia Vi Nau Bun Rieu Lal Mince Prawn in Spices.png' },
{ id: 56, name: 'Por Kwan Minced Bran in Spice', category: 'seafood', price: 1.99, description: 'Per unit', image: 'cannedimages/Por Kwan Minced Bran in Spice.png' },
{ id: 57, name: 'Wei Chuan Pickled Lettuce in Soy Sauce', category: 'pickled_fermented_foods', price: 3.99, description: 'Per unit', image: 'cannedimages/Wei Chuan Pickled Lettuce in Soy Sauce.png' },
{ id: 58, name: 'Hua Nan Pickled Lettuce in Soy Sauce', category: 'pickled_fermented_foods', price: 3.99, description: 'Per unit', image: 'cannedimages/Hua Nan Pickled Lettuce in Soy Sauce.png' },
{ id: 59, name: 'Hua Nan Pickled Cucumber in Soy Sauce', category: 'pickled_fermented_foods', price: 3.99, description: 'Per unit', image: 'cannedimages/Hua Nan Pickled Cucumber in Soy Sauce.png' },
{ id: 60, name: 'Hua Nan Strip Cucumber in Soy Sauce', category: 'pickled_fermented_foods', price: 3.99, description: 'Per unit', image: 'cannedimages/Hua Nan Strip Cucumber in Soy Sauce.png' },
{ id: 61, name: 'Hua Nan Sweet Ginger', category: 'pickled_fermented_foods', price: 3.99, description: 'Per unit', image: 'cannedimages/Hua Nan Sweet Ginger.png' },
{ id: 62, name: 'AGV Wulin Marinated Turnip', category: 'pickled_fermented_foods', price: 2.99, description: 'Per unit', image: 'cannedimages/AGV Wulin Marinated Turnip.png' },
{ id: 63, name: 'Golden Smell Bean Curd with Sesame Oil', category: 'pickled_fermented_foods', price: 3.99, description: 'Per unit', image: 'cannedimages/Golden Smell Bean Curd with Sesame Oil.png' },
{ id: 64, name: 'Pigeon Brand Pickled Mustard Green in Half in Soy Sauce', category: 'pickled_fermented_foods', price: 1.49, description: 'Per unit', image: 'cannedimages/Pigeon Brand Pickled Mustard Green in Half in Soy Sauce.png' },
{ id: 65, name: 'Pigeon Brand Fermented Lettuce', category: 'pickled_fermented_foods', price: 1.39, description: 'Per unit', image: 'cannedimages/Pigeon Brand Fermented Lettuce.png' },
{ id: 66, name: 'Pigeon Brand Pickled Sweetened Mustard Green', category: 'pickled_fermented_foods', price: 1.49, description: 'Per unit', image: 'cannedimages/Pigeon Brand Pickled Sweetened Mustard Green.png' },
{ id: 67, name: 'Pigeon Brand Fermented Hot & Sour Green Mustard Slices', category: 'pickled_fermented_foods', price: 1.49, description: 'Per unit', image: 'cannedimages/Pigeon Brand Fermented Hot & Sour Green Mustard Slices.png' },
{ id: 68, name: 'Flower Cured Pork Liver Pate', category: 'meat_poultry', price: 3.59, description: 'Per unit', image: 'cannedimages/Flower Cured Pork Liver Pate.png' },
{ id: 69, name: 'Goya Squid Pieces in Ink', category: 'seafood', price: 2.99, description: 'Per unit', image: 'cannedimages/Goya Squid Pieces in Ink.png' },

{ id: 70, name: 'Goya Squid Pieces in Ink Hot Sauce', category: 'seafood', price: 2.99, description: 'Per unit', image: 'cannedimages/Goya Squid Pieces in Ink Hot Sauce.png' },
{ id: 71, name: 'Goya Mussels in Pickled Sauce', category: 'seafood', price: 4.99, description: 'Per unit', image: 'cannedimages/Goya Mussels in Pickled Sauce.png' },
{ id: 72, name: 'Goya Jumbo Squid in Garlic Sauce', category: 'seafood', price: 3.99, description: 'Per unit', image: 'cannedimages/Goya Jumbo Squid in Garlic Sauce.png' },
{ id: 73, name: 'Goya Jumbo Squid in Hot Sauce', category: 'seafood', price: 3.99, description: 'Per unit', image: 'cannedimages/Goya Jumbo Squid in Hot Sauce.png' },
{ id: 74, name: 'Goya Octopus in Garlic Sauce', category: 'seafood', price: 6.99, description: 'Per unit', image: 'cannedimages/Goya Octopus in Garlic Sauce.png' },
{ id: 75, name: 'Celebrity Boneless Cooked Ham', category: 'meat_poultry', price: 5.99, description: 'Per unit', image: 'cannedimages/Celebrity Boneless Cooked Ham.png' },
{ id: 76, name: 'Argentina Luncheon Meat', category: 'meat_poultry', price: 4.99, description: 'Per unit', image: 'cannedimages/Argentina Luncheon Meat.png' },
{ id: 77, name: 'Maling Luncheon Loaf', category: 'meat_poultry', price: 4.99, description: 'Per unit', image: 'cannedimages/Maling Luncheon Loaf.png' },
{ id: 78, name: 'Asian Taste Luncheon Loaf', category: 'meat_poultry', price: 3.99, description: 'Per unit', image: 'cannedimages/Asian Taste Luncheon Loaf.png' },
{ id: 79, name: 'Ra’s Farm Luncheon Loaf Ham & Pork', category: 'meat_poultry', price: 4.99, description: 'Per unit', image: 'cannedimages/Ra’s Farm Luncheon Loaf Ham & Pork.png' },
{ id: 80, name: 'Ra’s Farm Luncheon Loaf Chicken & Pork', category: 'meat_poultry', price: 4.99, description: 'Per unit', image: 'cannedimages/Ra’s Farm Luncheon Loaf Chicken & Pork.png' },
{ id: 81, name: 'MaLing Ham Luncheon Meat', category: 'meat_poultry', price: 5.99, description: 'Per unit', image: 'cannedimages/MaLing Ham Luncheon Meat.png' },
{ id: 82, name: 'Fortune Luncheon Meat Pork & Ham', category: 'meat_poultry', price: 5.99, description: 'Per unit', image: 'cannedimages/Fortune Luncheon Meat Pork & Ham.png' },
{ id: 83, name: 'Kimbo Luncheon Meat Ham & Pork', category: 'meat_poultry', price: 4.99, description: 'Per unit', image: 'cannedimages/Kimbo Luncheon Meat Ham & Pork.png' },
{ id: 84, name: 'Celebrity Luncheon Meat Pork', category: 'meat_poultry', price: 4.99, description: 'Per unit', image: 'cannedimages/Celebrity Luncheon Meat Pork.png' },
{ id: 85, name: 'Ligo Luncheon Meat', category: 'meat_poultry', price: 5.99, description: 'Per unit', image: 'cannedimages/Ligo Luncheon Meat.png' },
{ id: 86, name: 'Wang Napa Kimchi Cabbage', category: 'pickled_fermented_foods', price: 2.59, description: 'Per unit', image: 'cannedimages/Wang Napa Kimchi Cabbage.png' },
{ id: 87, name: 'Napa Cabbage Kimchi Surasang', category: 'pickled_fermented_foods', price: 3.99, description: 'Per unit', image: 'cannedimages/Napa Cabbage Kimchi Surasang.png' },
{ id: 88, name: 'Wang Stir Fried Kimchi', category: 'pickled_fermented_foods', price: 2.59, description: 'Per unit', image: 'cannedimages/Wang Stir Fried Kimchi.png' },

{ id: 89, name: 'Wang Mustard Leaf Kimchi', category: 'pickled_fermented_foods', price: 2.59, description: 'Per unit', image: 'cannedimages/Wang Mustard Leaf Kimchi.png' },
{ id: 90, name: 'Nissui Mackerel in Soy Sauce', category: 'seafood', price: 3.99, description: 'Per unit', image: 'cannedimages/Nissui Mackerel in Soy Sauce.png' },
{ id: 91, name: 'Nissui Mackerel in Oil', category: 'seafood', price: 3.99, description: 'Per unit', image: 'cannedimages/Nissui Mackerel in Oil.png' },
{ id: 92, name: 'Nissui Mackerel in Soybean Paste', category: 'seafood', price: 3.99, description: 'Per unit', image: 'cannedimages/Nissui Mackerel in Soybean Paste.png' },
{ id: 93, name: 'Nissui Mackerel in Brine', category: 'seafood', price: 3.99, description: 'Per unit', image: 'cannedimages/Nissui Mackerel in Brine.png' },
{ id: 94, name: 'Victorias Foods Bangus Philippine Milkfish in Soya Oil', category: 'seafood', price: 3.49, description: 'Per unit', image: 'cannedimages/Victorias Foods Bangus Philippine Milkfish in Soya Oil.png' },
{ id: 95, name: 'YD Silkworm Pupa', category: 'exotic', price: 1.99, description: 'Per unit', image: 'cannedimages/YD Silkworm Pupa.png' },
{ id: 96, name: 'Sempio Cooked Silkworm Chrysalis', category: 'exotic', price: 1.99, description: 'Per unit', image: 'cannedimages/Sempio Cooked Silkworm Chrysalis.png' },
{ id: 97, name: 'Nissu Salmon Flakes', category: 'seafood', price: 7.99, description: 'Per unit', image: 'cannedimages/Nissu Salmon Flakes.png' },
{ id: 98, name: 'Shirakiku Canned Seasoned Fried Bean Curd', category: 'pickled_fermented_foods', price: 6.99, description: 'Per unit', image: 'cannedimages/Shirakiku Canned Seasoned Fried Bean Curd.png' },
{ id: 99, name: 'J Basket Seasoned Fried Bean Curd', category: 'pickled_fermented_foods', price: 5.99, description: 'Per unit', image: 'cannedimages/J Basket Seasoned Fried Bean Curd.png' },
{ id: 100, name: 'Bai Top Shell', category: 'seafood', price: 8.99, description: 'Per unit', image: 'cannedimages/Bai Top Shell.png' },
{ id: 101, name: 'YD Silkworm Pupa Soybean Paste', category: 'exotic', price: 3.59, description: 'Per unit', image: 'cannedimages/YD Silkworm Pupa Soybean Paste.png' },
{ id: 102, name: 'Por Kwan Minced Prawn In Spices', category: 'seafood', price: 4.99, description: 'Per unit', image: 'cannedimages/Por Kwan Minced Prawn In Spices.png' },
{ id: 103, name: 'Minced Prawn in Spices', category: 'seafood', price: 4.99, description: 'Per unit', image: 'cannedimages/Minced Prawn in Spices.png' },
{ id: 104, name: 'Lee Minced Prawn in Spices', category: 'seafood', price: 4.99, description: 'Per unit', image: 'cannedimages/Lee Minced Prawn in Spices.png' },
{ id: 105, name: 'Ocean Champ Minced Prawn in Spices', category: 'seafood', price: 4.99, description: 'Per unit', image: 'cannedimages/Ocean Champ Minced Prawn in Spices.png' },
{ id: 106, name: 'Por Kwan Minced Crab in Spices', category: 'seafood', price: 4.99, description: 'Per unit', image: 'cannedimages/Por Kwan Minced Crab in Spices.png' },
{ id: 107, name: 'Flower Brand Fancy White Crab Meat', category: 'seafood', price: 4.99, description: 'Per unit', image: 'cannedimages/Flower Brand Fancy White Crab Meat.png' },
{ id: 108, name: 'Morinaga Red Bean Paste', category: 'sweets_desserts', price: 5.99, description: 'Per unit', image: 'cannedimages/Morinaga Red Bean Paste.png' },
{ id: 109, name: 'Kabuto Red Bean Paste Koshian', category: 'sweets_desserts', price: 3.59, description: 'Per unit', image: 'cannedimages/Kabuto Red Bean Paste Koshian.png' },
{ id: 110, name: 'FSG Wild Bracken Pickles', category: 'pickled_fermented_foods', price: 3.99, description: 'Per unit', image: 'cannedimages/FSG Wild Bracken Pickles.png' },
 
{ id: 111, name: 'FSG Preserved Radish', category: 'pickled_fermented_foods', price: 3.99, description: 'Per unit', image: 'cannedimages/FSG Preserved Radish.png' },
{ id: 112, name: 'FSG Preserved Bamboo Shoot', category: 'pickled_fermented_foods', price: 3.99, description: 'Per unit', image: 'cannedimages/FSG Preserved Bamboo Shoot.png' },
{ id: 113, name: 'FSG Enoki Mushroom Pickles', category: 'pickled_fermented_foods', price: 3.99, description: 'Per unit', image: 'cannedimages/FSG Enoki Mushroom Pickles.png' },
{ id: 114, name: 'FSG Sichuan Pepper Pickles', category: 'pickled_fermented_foods', price: 3.99, description: 'Per unit', image: 'cannedimages/FSG Sichuan Pepper Pickles.png' },
{ id: 115, name: 'FSG Preserved Mushrooms', category: 'pickled_fermented_foods', price: 3.99, description: 'Per unit', image: 'cannedimages/FSG Preserved Mushrooms.png' },
{ id: 116, name: 'Hwang Ryh Shiang Fermented Chili Bean Curd with Minced Chili', category: 'pickled_fermented_foods', price: 3.99, description: 'Per unit', image: 'cannedimages/Hwang Ryh Shiang Fermented Chili Bean Curd with Minced Chili.png' },
{ id: 117, name: 'Hwang Ryh Shiang Fermented Chili Bean Curd in Dressing', category: 'pickled_fermented_foods', price: 3.59, description: 'Per unit', image: 'cannedimages/Hwang Ryh Shiang Fermented Chili Bean Curd in Dressing.png' },
{ id: 118, name: 'Wei Chuan White Fermented Bean Curd', category: 'pickled_fermented_foods', price: 3.99, description: 'Per unit', image: 'cannedimages/Wei Chuan White Fermented Bean Curd.png' },
{ id: 119, name: 'TF Szechuan Fermented Tofu', category: 'pickled_fermented_foods', price: 3.99, description: 'Per unit', image: 'cannedimages/TF Szechuan Fermented Tofu.png' },
{ id: 120, name: 'AFC Spicy with Sesame Oil Fermented Tofu Cubes in Brine', category: 'pickled_fermented_foods', price: 2.29, description: 'Per unit', image: 'cannedimages/AFC Spicy with Sesame Oil Fermented Tofu Cubes in Brine.png' },
{ id: 121, name: 'AFC Hot Chilli Beancurd', category: 'pickled_fermented_foods', price: 3.99, description: 'Per unit', image: 'cannedimages/AFC Hot Chilli Beancurd.png' },
{ id: 122, name: 'AFC Fermented Tofu Cubes with Sesame', category: 'pickled_fermented_foods', price: 3.99, description: 'Per unit', image: 'cannedimages/AFC Fermented Tofu Cubes with Sesame.png' },
{ id: 123, name: 'Wang Zhi He Fermented Traditional Beancurd', category: 'pickled_fermented_foods', price: 4.49, description: 'Per unit', image: 'cannedimages/Wang Zhi He Fermented Traditional Beancurd.png' },
{ id: 124, name: 'Haday Traditional Fermented Beancurd', category: 'pickled_fermented_foods', price: 3.99, description: 'Per unit', image: 'cannedimages/Haday Traditional Fermented Beancurd.png' },
{ id: 125, name: 'Hwang Ryh Shiang Fermented Bean Curd Chunks in Dressing with Red Yeast Rice', category: 'pickled_fermented_foods', price: 3.99, description: 'Per unit', image: 'cannedimages/Hwang Ryh Shiang Fermented Bean Curd Chunks in Dressing with Red Yeast Rice.png' },
{ id: 126, name: 'Pearl River Bridge Fermented Chili Bean Curd Tofu Fermentee Chili', category: 'pickled_fermented_foods', price: 3.99, description: 'Per unit', image: 'cannedimages/Pearl River Bridge Fermented Chili Bean Curd Tofu Fermentee Chili.png' },
{ id: 127, name: 'Pearl River Bridge Fermented Chili Bean Curd Tofu Fermentee', category: 'pickled_fermented_foods', price: 3.99, description: 'Per unit', image: 'cannedimages/Pearl River Bridge Fermented Chili Bean Curd Tofu Fermentee.png' },
{ id: 128, name: 'Henaff French Pork Liver Pate', category: 'meat_poultry', price: 3.99, description: 'Per unit', image: 'cannedimages/Henaff French Pork Liver Pate.png' },
{ id: 129, name: 'Henaff Pork Pate', category: 'meat_poultry', price: 5.99, description: 'Per unit', image: 'cannedimages/Henaff Pork Pate.png' },
{ id: 130, name: 'SPAM with Tocino seasoning', category: 'meat_poultry', price: 5.99, description: 'Per unit', image: 'cannedimages/SPAM with Tocino seasoning.png' },
{ id: 131, name: 'Assi Luncheon with Chicken & Pork', category: 'meat_poultry', price: 3.59, description: 'Per unit', image: 'cannedimages/Assi Luncheon with Chicken & Pork.png' },


{ id: 132, name: 'Dongwon Tuna Chunk Style in Sesame Oil', category: 'seafood', price: 12.99, description: 'Per unit', image: 'cannedimages/Dongwon Tuna Chunk Style in Sesame Oil.png' },
{ id: 133, name: 'Dongwon Tuna Chunk in Spicy Sesame Oil', category: 'seafood', price: 12.99, description: 'Per unit', image: 'cannedimages/Dongwon Tuna Chunk in Spicy Sesame Oil.png' },
{ id: 134, name: 'Dongwon Tuna 3 Can', category: 'seafood', price: 11.99, description: 'Per unit', image: 'cannedimages/Dongwon Tuna 3 Can.png' },
{ id: 135, name: 'Dongwon Tuna with Kimchi', category: 'seafood', price: 11.99, description: 'Per unit', image: 'cannedimages/Dongwon Tuna with Kimchi.png' },
{ id: 136, name: 'Dongwon Tuna with Vegetable 4 pack', category: 'seafood', price: 11.99, description: 'Per unit', image: 'cannedimages/Dongwon Tuna with Vegetable 4 pack.png' },
{ id: 137, name: 'Dongwon Tuna in Double Hot Pepper 4 pack', category: 'seafood', price: 11.99, description: 'Per unit', image: 'cannedimages/Dongwon Tuna in Double Hot Pepper 4 pack.png' },
{ id: 138, name: 'Dongwon Tuna with Hot Pepper Sauce', category: 'seafood', price: 11.99, description: 'Per unit', image: 'cannedimages/Dongwon Tuna with Hot Pepper Sauce.png' },
{ id: 139, name: 'Dongwon Canned Boiled Mackerel', category: 'seafood', price: 5.99, description: 'Per unit', image: 'cannedimages/Dongwon Canned Boiled Mackerel.png' },
{ id: 140, name: 'Penguin Mackerel Pike', category: 'seafood', price: 5.99, description: 'Per unit', image: 'cannedimages/Penguin Mackerel Pike.png' },
{ id: 141, name: 'Assi Mackerel Pike Boiled', category: 'seafood', price: 4.99, description: 'Per unit', image: 'cannedimages/Assi Mackerel Pike Boiled.png' },
{ id: 142, name: 'Dongwon Boiled Mackerel Pike', category: 'seafood', price: 5.99, description: 'Per unit', image: 'cannedimages/Dongwon Boiled Mackerel Pike.png' },
{ id: 143, name: 'Dongwon Rice Porridge with Tuna', category: 'broths_soups', price: 3.99, description: 'Per unit', image: 'cannedimages/Dongwon Rice Porridge with Tuna.png' },
{ id: 144, name: 'Dongwon Rice Porridge with Pine Nuts', category: 'broths_soups', price: 3.99, description: 'Per unit', image: 'cannedimages/Dongwon Rice Porridge with Pine Nuts.png' },
{ id: 145, name: 'Dongwon Rice Porridge with Abalone', category: 'broths_soups', price: 3.99, description: 'Per unit', image: 'cannedimages/Dongwon Rice Porridge with Abalone.png' },
{ id: 146, name: 'Dongwon Rice Porridge with Vegetables', category: 'broths_soups', price: 3.99, description: 'Per unit', image: 'cannedimages/Dongwon Rice Porridge with Vegetables.png' },
{ id: 147, name: 'Old Fisherman Roasted Eel', category: 'seafood', price: 2.59, description: 'Per unit', image: 'cannedimages/Old Fisherman Roasted Eel.png' },
{ id: 148, name: 'Asian Taste Roasted Eels with Fermented Black SoyBeans', category: 'seafood', price: 2.59, description: 'Per unit', image: 'cannedimages/Asian Taste Roasted Eels with Fermented Black SoyBeans.png' },
{ id: 149, name: 'Asian Taste Roasted Eels with Spicy Sauce', category: 'seafood', price: 2.59, description: 'Per unit', image: 'cannedimages/Asian Taste Roasted Eels with Spicy Sauce.png' },
{ id: 150, name: 'How Mama Canned Braised Eel Fermented', category: 'seafood', price: 2.59, description: 'Per unit', image: 'cannedimages/How Mama Canned Braised Eel Fermented.png' },
{ id: 151, name: 'J-Basket Sanma Kabayaki Seasoned and Broiled Saury', category: 'seafood', price: 3.59, description: 'Per unit', image: 'cannedimages/J-Basket Sanma Kabayaki Seasoned and Broiled Saury.png' },
{ id: 152, name: 'J Basket Saba Kabayaki Seasoned and Broiled Mackerel', category: 'seafood', price: 3.59, description: 'Per unit', image: 'cannedimages/J Basket Saba Kabayaki Seasoned and Broiled Mackerel.png' },
{ id: 153, name: 'ICC Sanma Kabayaki Saury Baked & Seasoned', category: 'seafood', price: 2.59, description: 'Per unit', image: 'cannedimages/ICC Sanma Kabayaki Saury Baked & Seasoned.png' },
{ id: 154, name: 'Sumaco Sardines in Tomato Sauce', category: 'seafood', price: 1.99, description: 'Per unit', image: 'cannedimages/Sumaco Sardines in Tomato Sauce.png' },
{ id: 155, name: 'Nissui Can Tuna Flake 3 Pack', category: 'seafood', price: 8.99, description: 'Per unit', image: 'cannedimages/Nissui Can Tuna Flake 3 Pack.png' },

{ id: 156, name: 'Nissui Canned Sardine In Sweet Soy Sauce', category: 'seafood', price: 3.49, description: 'Per unit', image: 'cannedimages/Nissui Canned Sardine In Sweet Soy Sauce.png' },
{ id: 157, name: 'Eagle Coin Spicy Fried Dace with Salted Black Beans and Pepper', category: 'seafood', price: 3.99, description: 'Per unit', image: 'cannedimages/Eagle Coin Spicy Fried Dace with Salted Black Beans and Pepper.png' },
{ id: 158, name: 'Eagle Coin Fried Dace with Olive Vegetable', category: 'seafood', price: 3.99, description: 'Per unit', image: 'cannedimages/Eagle Coin Fried Dace with Olive Vegetable.png' },
{ id: 159, name: 'Wangzhihe Sweet Red Bean Jam Paste', category: 'sweets_desserts', price: 3.59, description: 'Per unit', image: 'cannedimages/Wangzhihe Sweet Red Bean Jam Paste.png' },
{ id: 160, name: 'Taro Flavor Paste', category: 'sweets_desserts', price: 4.99, description: 'Per unit', image: 'cannedimages/Taro Flavor Paste.png' },
{ id: 161, name: 'Lotus Seed Paste', category: 'sweets_desserts', price: 3.99, description: 'Per unit', image: 'cannedimages/Lotus Seed Paste.png' },
{ id: 162, name: 'Havista Preserved Beancurd White', category: 'pickled_fermented_foods', price: 2.99, description: 'Per unit', image: 'cannedimages/Havista Preserved Beancurd White.png' },
{ id: 163, name: 'Havista Preserved Beancurd Spicy', category: 'pickled_fermented_foods', price: 2.99, description: 'Per unit', image: 'cannedimages/Havista Preserved Beancurd Spicy.png' },
{ id: 164, name: 'Havista Preserved Beancurd Red', category: 'pickled_fermented_foods', price: 2.99, description: 'Per unit', image: 'cannedimages/Havista Preserved Beancurd Red.png' },
{ id: 165, name: 'Liu Ma Kee Wet Beancurd', category: 'pickled_fermented_foods', price: 2.99, description: 'Per unit', image: 'cannedimages/Liu Ma Kee Wet Beancurd.png' },
{ id: 166, name: 'Tomo Foods Chili Baby Bamboo Shoot', category: 'vegetables', price: 2.99, description: 'Per unit', image: 'cannedimages/Tomo Foods Chili Baby Bamboo Shoot.png' },
{ id: 167, name: 'Tomo Foods Crispy Chili Bamboo Shoots', category: 'vegetables', price: 2.99, description: 'Per unit', image: 'cannedimages/Tomo Foods Crispy Chili Bamboo Shoots.png' },
{ id: 168, name: 'Master Pickled Lettuce', category: 'pickled_fermented_foods', price: 3.99, description: 'Per unit', image: 'cannedimages/Master Pickled Lettuce.png' },
{ id: 169, name: 'Kimlan Pickled Lettuce', category: 'pickled_fermented_foods', price: 3.99, description: 'Per unit', image: 'cannedimages/Kimlan Pickled Lettuce.png' },
{ id: 170, name: 'Kimlan Pickled Cucumber', category: 'pickled_fermented_foods', price: 3.99, description: 'Per unit', image: 'cannedimages/Kimlan Pickled Cucumber.png' },
{ id: 171, name: 'CMK Red Nam Bean Curd', category: 'pickled_fermented_foods', price: 3.99, description: 'Per unit', image: 'cannedimages/CMK Red Nam Bean Curd.png' },
{ id: 172, name: 'Master Peanut in Soy Sauce', category: 'pickled_fermented_foods', price: 3.99, description: 'Per unit', image: 'cannedimages/Master Peanut in Soy Sauce.png' },
{ id: 173, name: 'Kimlan Wheat Gluten', category: 'pickled_fermented_foods', price: 3.99, description: 'Per unit', image: 'cannedimages/Kimlan Wheat Gluten.png' },
{ id: 174, name: 'Por Kwan Vegetable Broth', category: 'broths_soups', price: 1.49, description: 'Per unit', image: 'cannedimages/Por Kwan Vegetable Broth.png' },
{ id: 175, name: 'New Choice Chicken Broth', category: 'broths_soups', price: 1.69, description: 'Per unit', image: 'cannedimages/New Choice Chicken Broth.png' },
{ id: 176, name: 'Porkwan Vegetable Broth', category: 'broths_soups', price: 3.59, description: 'Per unit', image: 'cannedimages/Porkwan Vegetable Broth.png' },
{ id: 177, name: 'L.A Lucky Vegetable Broth', category: 'broths_soups', price: 2.99, description: 'Per unit', image: 'cannedimages/L.A Lucky Vegetable Broth.png' },
{ id: 178, name: 'Asuka Baby Clams', category: 'seafood', price: 2.99, description: 'Per unit', image: 'cannedimages/Asuka Baby Clams.png' },
{ id: 179, name: 'Parrot Mackerel in Tomato Sauce', category: 'seafood', price: 3.59, description: 'Per unit', image: 'cannedimages/Parrot Mackerel in Tomato Sauce.png' },
{ id: 180, name: 'Parrot Mackerel in Brine', category: 'seafood', price: 3.59, description: 'Per unit', image: 'cannedimages/Parrot Mackerel in Brine.png' },
{ id: 181, name: '555 Tuna Flakes in Oil Hot & Spicy', category: 'seafood', price: 1.99, description: 'Per unit', image: 'cannedimages/555 Tuna Flakes in Oil Hot & Spicy.png' },
{ id: 182, name: '555 Tuna Flakes Calamansi', category: 'seafood', price: 1.99, description: 'Per unit', image: 'cannedimages/555 Tuna Flakes Calamansi.png' },
{ id: 183, name: '555 Tuna Flakes Caldereta', category: 'seafood', price: 1.99, description: 'Per unit', image: 'cannedimages/555 Tuna Flakes Caldereta.png' },
{ id: 184, name: '555 Tuna Flakes in Oil', category: 'seafood', price: 1.99, description: 'Per unit', image: 'cannedimages/555 Tuna Flakes in Oil.png' },
{ id: 185, name: '555 Tuna Flakes Afritada', category: 'seafood', price: 1.99, description: 'Per unit', image: 'cannedimages/555 Tuna Flakes Afritada.png' },
{ id: 186, name: '555 Tuna Flakes Mechado', category: 'seafood', price: 1.99, description: 'Per unit', image: 'cannedimages/555 Tuna Flakes Mechado.png' },
{ id: 187, name: '555 Spicy Bicol Express Tuna', category: 'seafood', price: 1.99, description: 'Per unit', image: 'cannedimages/555 Spicy Bicol Express Tuna.png' },
{ id: 188, name: 'Victorias Foods Hot Spanish in Soya Oil Sardines', category: 'seafood', price: 1.99, description: 'Per unit', image: 'cannedimages/Victorias Foods Hot Spanish in Soya Oil Sardines.png' },
{ id: 189, name: 'Ligo Sardines in Tomato Sauce', category: 'seafood', price: 2.99, description: 'Per unit', image: 'cannedimages/Ligo Sardines in Tomato Sauce.png' },
{ id: 190, name: 'Tropica Sardines in Tomato Sauce', category: 'seafood', price: 2.99, description: 'Per unit', image: 'cannedimages/Tropica Sardines in Tomato Sauce.png' },
{ id: 191, name: 'Tropica Sardines in Tomato Sauce with Chili', category: 'seafood', price: 2.99, description: 'Per unit', image: 'cannedimages/Tropica Sardines in Tomato Sauce with Chili.png' },
{ id: 192, name: 'Ligo Sardines in Chili Tomato Sauce', category: 'seafood', price: 1.29, description: 'Per unit', image: 'cannedimages/Ligo Sardines in Chili Tomato Sauce.png' },
{ id: 193, name: 'Victoria Hot Spanish in Soya Oil Sardines', category: 'seafood', price: 1.99, description: 'Per unit', image: 'cannedimages/Victoria Hot Spanish in Soya Oil Sardines.png' },
{ id: 194, name: 'Ligo Extra Hot Sardines', category: 'seafood', price: 1.29, description: 'Per unit', image: 'cannedimages/Ligo Extra Hot Sardines.png' },
{ id: 195, name: '555 Tuna Spicy Caldereta', category: 'seafood', price: 1.99, description: 'Per unit', image: 'cannedimages/555 Tuna Spicy Caldereta.png' },
{ id: 196, name: '555 Tuna Spicy Paksiw', category: 'seafood', price: 1.99, description: 'Per unit', image: 'cannedimages/555 Tuna Spicy Paksiw.png' },
{ id: 197, name: '555 Tuna Flakes Adobo', category: 'seafood', price: 1.99, description: 'Per unit', image: 'cannedimages/555 Tuna Flakes Adobo.png' },
{ id: 198, name: '555 Tuna Flakes Caldereta', category: 'seafood', price: 1.99, description: 'Per unit', image: 'cannedimages/555 Tuna Flakes Caldereta.png' },
{ id: 199, name: '555 Tuna Flakes Mechado', category: 'seafood', price: 1.99, description: 'Per unit', image: 'cannedimages/555 Tuna Flakes Mechado.png' },
{ id: 200, name: 'GW Preserved Vegetable', category: 'pickled_fermented_foods', price: 3.59, description: 'Per unit', image: 'cannedimages/GW Preserved Vegetable.png' },
{ id: 201, name: 'Preserved Cabbage Lychee Brand', category: 'pickled_fermented_foods', price: 2.99, description: 'Per unit', image: 'cannedimages/Preserved Cabbage Lychee Brand.png' },
{ id: 202, name: 'Porkwan Chicken Broth Soup', category: 'broths_soups', price: 2.99, description: 'Per unit', image: 'cannedimages/Porkwan Chicken Broth Soup.png' },
{ id: 203, name: 'Lee Chicken Broth', category: 'broths_soups', price: 2.99, description: 'Per unit', image: 'cannedimages/Lee Chicken Broth.png' },
{ id: 204, name: 'Porkwan Beef Flavored Broth', category: 'broths_soups', price: 3.49, description: 'Per unit', image: 'cannedimages/Porkwan Beef Flavored Broth.png' },
{ id: 205, name: 'Porkwan Spicy Beef Flavor Broth', category: 'broths_soups', price: 3.59, description: 'Per unit', image: 'cannedimages/Porkwan Spicy Beef Flavor Broth.png' },
{ id: 206, name: 'Lee Spicy Crab Soup', category: 'broths_soups', price: 2.99, description: 'Per unit', image: 'cannedimages/Lee Spicy Crab Soup.png' },
{ id: 207, name: 'Lee Tom Yum Kung Soup', category: 'broths_soups', price: 3.99, description: 'Per unit', image: 'cannedimages/Lee Tom Yum Kung Soup.png' },
{ id: 208, name: 'Lee Soup Bo Kho Spicy Stewed Beef Flavored Broth', category: 'broths_soups', price: 2.99, description: 'Per unit', image: 'cannedimages/Lee Soup Bo Kho Spicy Stewed Beef Flavored Broth.png' },
{ id: 209, name: 'Lee Spicy Beef Flavored Broth', category: 'broths_soups', price: 2.99, description: 'Per unit', image: 'cannedimages/Lee Spicy Beef Flavored Broth.png' },
{ id: 210, name: 'Ligo Hot Chili Sardines', category: 'seafood', price: 2.99, description: 'Per unit', image: 'cannedimages/Ligo Hot Chili Sardines.png' },
{ id: 211, name: 'Ligo Regular Sardines', category: 'seafood', price: 2.99, description: 'Per unit', image: 'cannedimages/Ligo Regular Sardines.png' },
{ id: 212, name: 'Ligo Squid in Natural Ink', category: 'seafood', price: 4.99, description: 'Per unit', image: 'cannedimages/Ligo Squid in Natural Ink.png' },
{ id: 213, name: 'Ligo Fancy Alaska Pink Salmon', category: 'seafood', price: 5.99, description: 'Per unit', image: 'cannedimages/Ligo Fancy Alaska Pink Salmon.png' },
{ id: 214, name: 'Dongwon Baitop Shell Hot', category: 'seafood', price: 9.99, description: 'Per unit', image: 'cannedimages/Dongwon Baitop Shell Hot.png' },
{ id: 215, name: 'Old Fisherman Mackerel in Chili Tomato', category: 'seafood', price: 2.59, description: 'Per unit', image: 'cannedimages/Old Fisherman Mackerel in Chili Tomato.png' },
{ id: 216, name: 'Roasted Eel with Fermented Black Beans', category: 'seafood', price: 2.59, description: 'Per unit', image: 'cannedimages/Roasted Eel with Fermented Black Beans.png' },
{ id: 217, name: 'Old Fisherman Roasted Eel with Black Pepper', category: 'seafood', price: 2.59, description: 'Per unit', image: 'cannedimages/Old Fisherman Roasted Eel with Black Pepper.png' },
{ id: 218, name: 'Wu Chung Vegetarian Mock Duck', category: 'meat_poultry', price: 2.99, description: 'Per unit', image: 'cannedimages/Wu Chung Vegetarian Mock Duck.png' },
{ id: 219, name: 'Wu Chung Bamboo Shoot Tips with Chilli', category: 'vegetables', price: 2.99, description: 'Per unit', image: 'cannedimages/Wu Chung Bamboo Shoot Tips with Chilli.png' },
{ id: 220, name: 'Wu Chung Vegetarian Chop Suey', category: 'vegetables', price: 2.99, description: 'Per unit', image: 'cannedimages/Wu Chung Vegetarian Chop Suey.png' },
{ id: 221, name: 'Wu Chung Vegetarian Mock Pork', category: 'meat_poultry', price: 2.99, description: 'Per unit', image: 'cannedimages/Wu Chung Vegetarian Mock Pork.png' },
{ id: 222, name: 'Wu Chung Chai Charng Braised Gluten', category: 'pickled_fermented_foods', price: 2.99, description: 'Per unit', image: 'cannedimages/Wu Chung Chai Charng Braised Gluten.png' },
{ id: 223, name: 'Wu Chung Vegetarian Szu Hsien Kaw Fu', category: 'pickled_fermented_foods', price: 2.99, description: 'Per unit', image: 'cannedimages/Wu Chung Vegetarian Szu Hsien Kaw Fu.png' },
{ id: 224, name: 'Wu Chung Vegetarian Mushrooms & Bamboo', category: 'vegetables', price: 2.99, description: 'Per unit', image: 'cannedimages/Wu Chung Vegetarian Mushrooms & Bamboo.png' },
{ id: 225, name: 'Wu Chung Vegetarian Steak and Vegetables', category: 'meat_poultry', price: 2.99, description: 'Per unit', image: 'cannedimages/Wu Chung Vegetarian Steak and Vegetables.png' },
{ id: 226, name: 'Wu Chung Fried Gluten With Mushroom and Peanut', category: 'pickled_fermented_foods', price: 2.99, description: 'Per unit', image: 'cannedimages/Wu Chung Fried Gluten With Mushroom and Peanut.png' },
{ id: 227, name: 'Wu Chung Chai Pow Yu with Curry', category: 'vegetables', price: 2.99, description: 'Per unit', image: 'cannedimages/Wu Chung Chai Pow Yu with Curry.png' },
{ id: 228, name: 'Wu Chung Vegetarian Lo Han Chai', category: 'vegetables', price: 2.99, description: 'Per unit', image: 'cannedimages/Wu Chung Vegetarian Lo Han Chai.png' },
{ id: 229, name: 'Wu Chung Vegetarian Mock Chicken', category: 'meat_poultry', price: 2.99, description: 'Per unit', image: 'cannedimages/Wu Chung Vegetarian Mock Chicken.png' },
{ id: 230, name: 'Saline Bamboo Shoots', category: 'vegetables', price: 2.99, description: 'Per unit', image: 'cannedimages/Saline Bamboo Shoots.png' },
{ id: 231, name: 'D-Horse Sweeten Radish Whole', category: 'pickled_fermented_foods', price: 3.99, description: 'Per unit', image: 'cannedimages/D-Horse Sweeten Radish Whole.png' },
{ id: 232, name: 'D-Horse Salted Radish Whole', category: 'pickled_fermented_foods', price: 3.99, description: 'Per unit', image: 'cannedimages/D-Horse Salted Radish Whole.png' },
{ id: 233, name: 'D-Horse Sweeten Radish Strip', category: 'pickled_fermented_foods', price: 3.99, description: 'Per unit', image: 'cannedimages/D-Horse Sweeten Radish Strip.png' },
{ id: 234, name: 'D-Horse Salted Radish Strip', category: 'pickled_fermented_foods', price: 3.99, description: 'Per unit', image: 'cannedimages/D-Horse Salted Radish Strip.png' },
{ id: 235, name: 'First World Whole Salted Radish', category: 'pickled_fermented_foods', price: 2.59, description: 'Per unit', image: 'cannedimages/First World Whole Salted Radish.png' },
{ id: 236, name: 'First World Whole Sweetened Radish', category: 'pickled_fermented_foods', price: 2.59, description: 'Per unit', image: 'cannedimages/First World Whole Sweetened Radish.png' },
{ id: 237, name: 'Haetae Korean Noodle Soup', category: 'broths_soups', price: 1.59, description: 'Per unit', image: 'cannedimages/Haetae Korean Noodle Soup.png' },
{ id: 238, name: 'Golden Smell Preserved Turnip Strip', category: 'pickled_fermented_foods', price: 1.99, description: 'Per unit', image: 'cannedimages/Golden Smell Preserved Turnip Strip.png' },
{ id: 239, name: 'Sweet Preserved Turnip', category: 'pickled_fermented_foods', price: 2.99, description: 'Per unit', image: 'cannedimages/Sweet Preserved Turnip.png' },
{ id: 240, name: 'Salty Preserved Turnip', category: 'pickled_fermented_foods', price: 2.99, description: 'Per unit', image: 'cannedimages/Salty Preserved Turnip.png' },
{ id: 241, name: 'Yi Feng Crisp Bamboo Shoots', category: 'vegetables', price: 6.99, description: 'Per unit', image: 'cannedimages/Yi Feng Crisp Bamboo Shoots.png' },
{ id: 242, name: 'Marque Papaya Tree Brand Dried Bamboo Shoot', category: 'vegetables', price: 3.99, description: 'Per unit', image: 'cannedimages/Marque Papaya Tree Brand Dried Bamboo Shoot.png' },
{ id: 243, name: 'BT Dried Bamboo Shoot Mang', category: 'vegetables', price: 7.99, description: 'Per unit', image: 'cannedimages/BT Dried Bamboo Shoot Mang.png' },
{ id: 244, name: 'Heng Lung Dried Olive in Pieces', category: 'pickled_fermented_foods', price: 1.99, description: 'Per unit', image: 'cannedimages/Heng Lung Dried Olive in Pieces.png' },
{ id: 245, name: 'Dried Radish Seche', category: 'pickled_fermented_foods', price: 1.89, description: 'Per unit', image: 'cannedimages/Dried Radish Seche.png' },
{ id: 246, name: 'Aroy - D Lait De Coconut Milk', category: 'dairy_creamers', price: 1.99, description: 'Per unit', image: 'cannedimages/Aroy - D Lait De Coconut Milk.png' },
{ id: 247, name: 'Coco King Coconut Milk 17%', category: 'dairy_creamers', price: 1.99, description: 'Per unit', image: 'cannedimages/Coco King Coconut Milk 17%.png' },
{ id: 248, name: 'Coco King Coconut Milk 22%', category: 'dairy_creamers', price: 1.99, description: 'Per unit', image: 'cannedimages/Coco King Coconut Milk 22%.png' },
{ id: 249, name: 'Chef’s Choice Coconut Whipping Cream', category: 'dairy_creamers', price: 2.99, description: 'Per unit', image: 'cannedimages/Chef’s Choice Coconut Whipping Cream.png' },
{ id: 250, name: 'Chef’s Choice Evaporated Coconut Milk', category: 'dairy_creamers', price: 2.99, description: 'Per unit', image: 'cannedimages/Chef’s Choice Evaporated Coconut Milk.png' },

{ id: 251, name: 'Aroy - D Coconut Milk', category: 'dairy_creamers', price: 0.99, description: 'Per unit', image: 'cannedimages/Aroy - D Coconut Milk.png' },
{ id: 252, name: 'Excellence Lemon Vinegar', category: 'pickled_fermented_foods', price: 5.99, description: 'Per unit', image: 'cannedimages/Excellence Lemon Vinegar.png' },
{ id: 253, name: 'Excellence Plum Vinegar', category: 'pickled_fermented_foods', price: 5.99, description: 'Per unit', image: 'cannedimages/Excellence Plum Vinegar.png' },
{ id: 254, name: 'Excellence Apple Vinegar', category: 'pickled_fermented_foods', price: 5.99, description: 'Per unit', image: 'cannedimages/Excellence Apple Vinegar.png' },
{ id: 255, name: 'Houston Cowboy Pandan Syrup', category: 'oils_extracts', price: 6.99, description: 'Per unit', image: 'cannedimages/Houston Cowboy Pandan Syrup.png' },
{ id: 256, name: 'Hale’s Blue Boy Green Cream Soda Flavored Syrup', category: 'sweets_desserts', price: 5.99, description: 'Per unit', image: 'cannedimages/Hale’s Blue Boy Green Cream Soda Flavored Syrup.png' },
{ id: 257, name: 'Hale’s Red Sala Flavored Syrup', category: 'sweets_desserts', price: 5.99, description: 'Per unit', image: 'cannedimages/Hale’s Red Sala Flavored Syrup.png' },
{ id: 258, name: 'Kong Yen Plum Vinegar', category: 'pickled_fermented_foods', price: 8.99, description: 'Per unit', image: 'cannedimages/Kong Yen Plum Vinegar.png' },
{ id: 259, name: 'Kong Yen Apple Vinegar', category: 'pickled_fermented_foods', price: 8.99, description: 'Per unit', image: 'cannedimages/Kong Yen Apple Vinegar.png' },
{ id: 260, name: 'Surasang Plum Extract', category: 'oils_extracts', price: 22.99, description: 'Per unit', image: 'cannedimages/Surasang Plum Extract.png' },
{ id: 261, name: 'TruSweet Allulose Oligosaccharides Syrup', category: 'oils_extracts', price: 9.99, description: 'Per unit', image: 'cannedimages/TruSweet Allulose Oligosaccharides Syrup.png' },
{ id: 262, name: 'Assi Corn Syrup', category: 'oils_extracts', price: 7.99, description: 'Per unit', image: 'cannedimages/Assi Corn Syrup.png' },
{ id: 263, name: 'Dragonfly Lime Juice', category: 'sweets_desserts', price: 4.80, description: 'Per unit', image: 'cannedimages/Dragonfly Lime Juice.png' },
{ id: 264, name: 'Wang Corn Syrup', category: 'oils_extracts', price: 5.99, description: 'Per unit', image: 'cannedimages/Wang Corn Syrup.png' },
{ id: 265, name: 'Chungjungone Cooking Oligo Syrup', category: 'oils_extracts', price: 7.99, description: 'Per unit', image: 'cannedimages/Chungjungone Cooking Oligo Syrup.png' },
{ id: 266, name: 'Ottogi Korean Rice Syrup', category: 'oils_extracts', price: 19.99, description: 'Per unit', image: 'cannedimages/Ottogi Korean Rice Syrup.png' },
{ id: 267, name: 'AT AI-Yu Jelly', category: 'sweets_desserts', price: 1.99, description: 'Per unit', image: 'cannedimages/AT AI-Yu Jelly.png' },
{ id: 268, name: 'Chin Chin AI-Yu Jelly', category: 'sweets_desserts', price: 2.79, description: 'Per unit', image: 'cannedimages/Chin Chin AI-Yu Jelly.png' },
{ id: 269, name: 'Golden King AI-Yu Jelly', category: 'sweets_desserts', price: 3.59, description: 'Per unit', image: 'cannedimages/Golden King AI-Yu Jelly.png' },
{ id: 270, name: 'Chef’s Choice Passionfruit Pulp in Syrup', category: 'sweets_desserts', price: 2.59, description: 'Per unit', image: 'cannedimages/Chef’s Choice Passionfruit Pulp in Syrup.png' },
{ id: 271, name: 'Asian Best Stir Fry Mixed Vegetables', category: 'vegetables', price: 2.59, description: 'Per unit', image: 'cannedimages/Asian Best Stir Fry Mixed Vegetables.png' },
{ id: 272, name: 'Maesri Bai Yanang Leaves Extract', category: 'oils_extracts', price: 2.99, description: 'Per unit', image: 'cannedimages/Maesri Bai Yanang Leaves Extract.png' },
{ id: 273, name: 'Maesri Pandan Leaves Extract', category: 'oils_extracts', price: 2.99, description: 'Per unit', image: 'cannedimages/Maesri Pandan Leaves Extract.png' },
{ id: 274, name: 'Lee Pandan Leaves Extract', category: 'oils_extracts', price: 1.99, description: 'Per unit', image: 'cannedimages/Lee Pandan Leaves Extract.png' },

{ id: 275, name: 'L.A. Lucky Coconut Juice', category: 'juice', price: 1.79, description: 'Per unit', image: 'cannedimages/L.A. Lucky Coconut Juice.png' },
{ id: 276, name: 'L.A. Lucky Pandan Leaves Extract', category: 'oils_extracts', price: 2.59, description: 'Per unit', image: 'cannedimages/L.A. Lucky Pandan Leaves Extract.png' },
{ id: 277, name: 'TKS Cut Baby Corn', category: 'vegetables', price: 1.99, description: 'Per unit', image: 'cannedimages/TKS Cut Baby Corn.png' },
{ id: 278, name: 'Ligo Cream Style Corn', category: 'vegetables', price: 1.99, description: 'Per unit', image: 'cannedimages/Ligo Cream Style Corn.png' },
{ id: 279, name: 'Aroy - D Young Baby Corn in Brine', category: 'vegetables', price: 2.79, description: 'Per unit', image: 'cannedimages/Aroy - D Young Baby Corn in Brine.png' },
{ id: 280, name: 'Asian Best Whole Bamboo Shoots in Water', category: 'vegetables', price: 2.99, description: 'Per unit', image: 'cannedimages/Asian Best Whole Bamboo Shoots in Water.png' },

{ id: 281, name: 'Asian Best Whole Young Corn in Brine', category: 'vegetables', price: 2.29, description: 'Per unit', image: 'cannedimages/Asian Best Whole Young Corn in Brine.png' },
{ id: 282, name: 'Asian Best Cut Young Corn in Brine', category: 'vegetables', price: 1.99, description: 'Per unit', image: 'cannedimages/Asian Best Cut Young Corn in Brine.png' },
{ id: 283, name: 'Hunsty Whole Bamboo Shoot', category: 'vegetables', price: 2.99, description: 'Per unit', image: 'cannedimages/Hunsty Whole Bamboo Shoot.png' },
{ id: 284, name: 'Aroy - D Young Coconut Meat', category: 'dairy_creamers', price: 2.99, description: 'Per unit', image: 'cannedimages/Aroy - D Young Coconut Meat.png' },
{ id: 285, name: 'Chaokoh Coconut Milk', category: 'dairy_creamers', price: 1.99, description: 'Per unit', image: 'cannedimages/Chaokoh Coconut Milk.png' },
{ id: 286, name: 'Savoy Coconut Cream', category: 'dairy_creamers', price: 2.99, description: 'Per unit', image: 'cannedimages/Savoy Coconut Cream.png' },
{ id: 287, name: 'Aroy - D Coconut Milk', category: 'dairy_creamers', price: 2.29, description: 'Per unit', image: 'cannedimages/Aroy - D Coconut Milk.png' },
{ id: 288, name: 'Sunvoi Coconut Milk', category: 'dairy_creamers', price: 1.59, description: 'Per unit', image: 'cannedimages/Sunvoi Coconut Milk.png' },
{ id: 289, name: 'Mae Ploy Coconut Cream', category: 'dairy_creamers', price: 2.99, description: 'Per unit', image: 'cannedimages/Mae Ploy Coconut Cream.png' },
{ id: 290, name: 'Sago Tapioca Pearl In Syrup', category: 'sweets_desserts', price: 2.99, description: 'Per unit', image: 'cannedimages/Sago Tapioca Pearl In Syrup.png' },
{ id: 291, name: 'Buenas Sago Tapioca Pearl in Syrup', category: 'sweets_desserts', price: 2.99, description: 'Per unit', image: 'cannedimages/Buenas Sago Tapioca Pearl in Syrup.png' },
{ id: 292, name: 'Buenas Coconut Gel Nata De Coco in Syrup', category: 'sweets_desserts', price: 2.99, description: 'Per unit', image: 'cannedimages/Buenas Coconut Gel Nata De Coco in Syrup.png' },
{ id: 293, name: 'Tropica ChickPeas in Syrup', category: 'sweets_desserts', price: 4.99, description: 'Per unit', image: 'cannedimages/Tropica ChickPeas in Syrup.png' },
{ id: 294, name: 'Ning Chi Skinned Green Chili Peppers', category: 'vegetables', price: 3.97, description: 'Per unit', image: 'cannedimages/Ning Chi Skinned Green Chili Peppers.png' },
{ id: 295, name: 'Coconut Tree Sweet Sour Sauce', category: 'sauces_pastes', price: 3.99, description: 'Per unit', image: 'cannedimages/Coconut Tree Sweet Sour Sauce.png' },
{ id: 296, name: 'Pickled Millet Chili in Brine', category: 'pickled_fermented_foods', price: 2.99, description: 'Per unit', image: 'cannedimages/Pickled Millet Chili in Brine.png' },
{ id: 297, name: 'Khamphouk Dahendi in Brine', category: 'pickled_fermented_foods', price: 5.90, description: 'Per unit', image: 'cannedimages/Khamphouk Dahendi in Brine.png' },
{ id: 298, name: 'Chef’s Choice Aloe Vera in Syrup', category: 'sweets_desserts', price: 2.99, description: 'Per unit', image: 'cannedimages/Chef’s Choice Aloe Vera in Syrup.png' },
{ id: 299, name: 'Chef’s Choice Aloe Vera in Grape Syrup', category: 'sweets_desserts', price: 2.99, description: 'Per unit', image: 'cannedimages/Chef’s Choice Aloe Vera in Grape Syrup.png' },
{ id: 300, name: 'Lamthong Toddy Palm & Jackfruit in Syrup', category: 'sweets_desserts', price: 3.99, description: 'Per unit', image: 'cannedimages/Lamthong Toddy Palm & Jackfruit in Syrup.png' },
{ id: 301, name: 'Whole Seedless Lychee', category: 'fruits', price: 3.99, description: 'Per unit', image: 'cannedimages/Whole Seedless Lychee.png' },
{ id: 302, name: 'Lotus Lychees in Heavy Syrup', category: 'fruits', price: 3.99, description: 'Per unit', image: 'cannedimages/Lotus Lychees in Heavy Syrup.png' },
{ id: 303, name: 'Pigeon Rambutan in Syrup', category: 'fruits', price: 3.99, description: 'Per unit', image: 'cannedimages/Pigeon Rambutan in Syrup.png' },
{ id: 304, name: 'Sun Voi Lychee in Syrup', category: 'fruits', price: 3.99, description: 'Per unit', image: 'cannedimages/Sun Voi Lychee in Syrup.png' },
{ id: 305, name: 'Pigeon Whole Lychees in Heavy Syrup', category: 'fruits', price: 3.99, description: 'Per unit', image: 'cannedimages/Pigeon Whole Lychees in Heavy Syrup.png' },
{ id: 306, name: 'Aroy - D Toddy Palm’s Seed Slices in Syrup', category: 'fruits', price: 4.99, description: 'Per unit', image: 'cannedimages/Aroy - D Toddy Palm’s Seed Slices in Syrup.png' },
{ id: 307, name: 'Aroy - D Toddy Palm Seed Whole in Syrup', category: 'fruits', price: 4.99, description: 'Per unit', image: 'cannedimages/Aroy - D Toddy Palm Seed Whole in Syrup.png' },
{ id: 308, name: 'Aroy - D Toddy Palms Seed & Jackfruit in Syrup', category: 'fruits', price: 4.99, description: 'Per unit', image: 'cannedimages/Aroy - D Toddy Palms Seed & Jackfruit in Syrup.png' },
{ id: 309, name: 'Daily Farm Sweetened Condensed Creamer', category: 'dairy_creamers', price: 2.99, description: 'Per unit', image: 'cannedimages/Daily Farm Sweetened Condensed Creamer.png' },
{ id: 310, name: 'Black & White Extra Creamy Evaporated Milk', category: 'dairy_creamers', price: 2.99, description: 'Per unit', image: 'cannedimages/Black & White Extra Creamy Evaporated Milk.png' },

{ id: 311, name: 'California Farms Sweetened Condensed Creamer', category: 'dairy_creamers', price: 2.99, description: 'Per unit', image: 'cannedimages/California Farms Sweetened Condensed Creamer.png' },
{ id: 312, name: 'Chef’s Choice Sweetened Condensed Coconut Milk', category: 'dairy_creamers', price: 2.99, description: 'Per unit', image: 'cannedimages/Chef’s Choice Sweetened Condensed Coconut Milk.png' },
{ id: 313, name: 'Aroy - D Organic Coconut Milk', category: 'dairy_creamers', price: 2.99, description: 'Per unit', image: 'cannedimages/Aroy - D Organic Coconut Milk.png' },
{ id: 314, name: 'Longevity Gold Sweetened Condensed Milk', category: 'dairy_creamers', price: 4.99, description: 'Per unit', image: 'cannedimages/Longevity Gold Sweetened Condensed Milk.png' },
{ id: 315, name: 'Longevity Sweetened Condensed Milk', category: 'dairy_creamers', price: 4.99, description: 'Per unit', image: 'cannedimages/Longevity Sweetened Condensed Milk.png' },
{ id: 316, name: 'Parrot Evaporated Milk Filled', category: 'dairy_creamers', price: 2.59, description: 'Per unit', image: 'cannedimages/Parrot Evaporated Milk Filled.png' },
{ id: 317, name: 'Chaokoh Sweetened Condensed Coconut Milk', category: 'dairy_creamers', price: 3.59, description: 'Per unit', image: 'cannedimages/Chaokoh Sweetened Condensed Coconut Milk.png' },
{ id: 318, name: 'Chaokoh Evaporated Coconut Milk', category: 'dairy_creamers', price: 2.99, description: 'Per unit', image: 'cannedimages/Chaokoh Evaporated Coconut Milk.png' },
{ id: 319, name: 'Jans Sweet Cow Sweetened Condensed Creamer', category: 'dairy_creamers', price: 2.99, description: 'Per unit', image: 'cannedimages/Jans Sweet Cow Sweetened Condensed Creamer.png' },
{ id: 320, name: 'Southern Star Sweetened Condensed Creamer', category: 'dairy_creamers', price: 2.99, description: 'Per unit', image: 'cannedimages/Southern Star Sweetened Condensed Creamer.png' },
{ id: 321, name: 'California Farms Salted Caramel Sauce', category: 'sauces_pastes', price: 6.99, description: 'Per unit', image: 'cannedimages/California Farms Salted Caramel Sauce.png' },
{ id: 322, name: 'California Farms Chocolate Sauce', category: 'sauces_pastes', price: 6.99, description: 'Per unit', image: 'cannedimages/California Farms Chocolate Sauce.png' },
{ id: 323, name: 'California Farms Blue Condensed Creamer', category: 'dairy_creamers', price: 3.99, description: 'Per unit', image: 'cannedimages/California Farms Blue Condensed Creamer.png' },
{ id: 324, name: 'California Farm Red Condensed Creamer Full Cream', category: 'dairy_creamers', price: 4.99, description: 'Per unit', image: 'cannedimages/California Farm Red Condensed Creamer Full Cream.png' },
{ id: 325, name: 'Asian Taste Quail Eggs', category: 'eggs', price: 3.59, description: 'Per unit', image: 'cannedimages/Asian Taste Quail Eggs.png' },
{ id: 326, name: 'Dragonfly Salted Crataeva Nurvala', category: 'pickled_fermented_foods', price: 5.99, description: 'Per unit', image: 'cannedimages/Dragonfly Salted Crataeva Nurvala.png' },
{ id: 327, name: 'Dragonfly Pickled Rhizome', category: 'pickled_fermented_foods', price: 4.99, description: 'Per unit', image: 'cannedimages/Dragonfly Pickled Rhizome.png' },
{ id: 328, name: 'LA Lucky Whole Pickled Krachai', category: 'pickled_fermented_foods', price: 2.99, description: 'Per unit', image: 'cannedimages/LA Lucky Whole Pickled Krachai.png' },
{ id: 329, name: 'JHC Pickled Whole Galinga', category: 'pickled_fermented_foods', price: 3.99, description: 'Per unit', image: 'cannedimages/JHC Pickled Whole Galinga.png' },
{ id: 330, name: 'Siam Select Pickled Krachai in Brine', category: 'pickled_fermented_foods', price: 1.68, description: 'Per unit', image: 'cannedimages/Siam Select Pickled Krachai in Brine.png' },
{ id: 331, name: 'Siam Select Pickled Garlic in Brine', category: 'pickled_fermented_foods', price: 4.99, description: 'Per unit', image: 'cannedimages/Siam Select Pickled Garlic in Brine.png' },
{ id: 332, name: 'Kamayan Hala - Hala Mix Fruit', category: 'fruits', price: 3.99, description: 'Per unit', image: 'cannedimages/Kamayan Hala - Hala Mix Fruit.png' },
{ id: 333, name: 'Kamayan Langka Jackfruit in Syrup', category: 'fruits', price: 4.99, description: 'Per unit', image: 'cannedimages/Kamayan Langka Jackfruit in Syrup.png' },
{ id: 334, name: 'Tropica Jackfruit Pulp in Syrup Langka', category: 'fruits', price: 4.99, description: 'Per unit', image: 'cannedimages/Tropica Jackfruit Pulp in Syrup Langka.png' },
{ id: 335, name: 'Tropica Tapioca Pearls in Syrup', category: 'sweets_desserts', price: 3.59, description: 'Per unit', image: 'cannedimages/Tropica Tapioca Pearls in Syrup.png' },
{ id: 336, name: 'Chow - Q Fruit Mix in Syrup', category: 'fruits', price: 3.99, description: 'Per unit', image: 'cannedimages/Chow - Q Fruit Mix in Syrup.png' },
{ id: 337, name: 'Asian Taste Longan in Syrup', category: 'fruits', price: 3.99, description: 'Per unit', image: 'cannedimages/Asian Taste Longan in Syrup.png' },
{ id: 338, name: 'Aroy - D Papaya in Syrup', category: 'fruits', price: 2.99, description: 'Per unit', image: 'cannedimages/Aroy - D Papaya in Syrup.png' },
{ id: 339, name: 'Aroy - D Sugar Cane in Light Syrup', category: 'fruits', price: 3.59, description: 'Per unit', image: 'cannedimages/Aroy - D Sugar Cane in Light Syrup.png' },
{ id: 340, name: 'Aroy - D Rambutan in Syrup', category: 'fruits', price: 5.99, description: 'Per unit', image: 'cannedimages/Aroy - D Rambutan in Syrup.png' },
{ id: 341, name: 'Asian Best Rambutan in Syrup', category: 'fruits', price: 4.99, description: 'Per unit', image: 'cannedimages/Asian Best Rambutan in Syrup.png' },

{ id: 342, name: 'Aroy - D Lychee in Syrup', category: 'fruits', price: 5.99, description: 'Per unit', image: 'cannedimages/Aroy - D Lychee in Syrup.png' },
{ id: 343, name: 'TKS Whole Baby Corn', category: 'vegetables', price: 2.29, description: 'Per unit', image: 'cannedimages/TKS Whole Baby Corn.png' },
{ id: 344, name: 'TKS Broken Straw Mushrooms', category: 'vegetables', price: 2.49, description: 'Per unit', image: 'cannedimages/TKS Broken Straw Mushrooms.png' },
{ id: 345, name: 'TKS Peeled Straw Mushrooms', category: 'vegetables', price: 2.99, description: 'Per unit', image: 'cannedimages/TKS Peeled Straw Mushrooms.png' },
{ id: 346, name: 'TKS Unpeeled Straw Mushrooms', category: 'vegetables', price: 2.59, description: 'Per unit', image: 'cannedimages/TKS Unpeeled Straw Mushrooms.png' },
{ id: 347, name: 'Asian Best Peeled Straw Mushroom Broken', category: 'vegetables', price: 2.59, description: 'Per unit', image: 'cannedimages/Asian Best Peeled Straw Mushroom Broken.png' },
{ id: 348, name: 'Lucky Crown Straw Mushroom Whole Peeled', category: 'vegetables', price: 3.99, description: 'Per unit', image: 'cannedimages/Lucky Crown Straw Mushroom Whole Peeled.png' },
{ id: 349, name: 'Asian Taste Peeled Straw Mushroom', category: 'vegetables', price: 3.59, description: 'Per unit', image: 'cannedimages/Asian Taste Peeled Straw Mushroom.png' },
{ id: 350, name: 'Asian Taste Broken Straw Mushroom', category: 'vegetables', price: 3.59, description: 'Per unit', image: 'cannedimages/Asian Taste Broken Straw Mushroom.png' },
{ id: 351, name: 'Assi Sweetened Chestnut Can', category: 'nuts', price: 4.99, description: 'Per unit', image: 'cannedimages/Assi Sweetened Chestnut Can.png' },
{ id: 352, name: 'Asian Best Whole Water Chestnuts', category: 'vegetables', price: 1.99, description: 'Per unit', image: 'cannedimages/Asian Best Whole Water Chestnuts.png' },
{ id: 353, name: 'Wei Chuan Whole Water Chestnuts', category: 'vegetables', price: 1.99, description: 'Per unit', image: 'cannedimages/Wei Chuan Whole Water Chestnuts.png' },
{ id: 354, name: 'Southern Star Sweetened Condensed Creamer', category: 'dairy', price: 5.99, description: 'Per unit', image: 'cannedimages/Southern Star Sweetened Condensed Creamer.png' },
{ id: 355, name: 'Smaller Southern Star Sweetened Condensed Creamer', category: 'dairy', price: 2.99, description: 'Per unit', image: 'cannedimages/Smaller Southern Star Sweetened Condensed Creamer.png' },
{ id: 356, name: 'Aroy - D UHT Coconut Cream', category: 'dairy', price: 3.99, description: 'Per unit', image: 'cannedimages/Aroy - D UHT Coconut Cream.png' },
{ id: 357, name: 'Aroy - D UHT Original Coconut Milk', category: 'dairy', price: 3.99, description: 'Per unit', image: 'cannedimages/Aroy - D UHT Original Coconut Milk.png' },
{ id: 358, name: 'Kara Coconut Cream', category: 'dairy', price: 6.99, description: 'Per unit', image: 'cannedimages/Kara Coconut Cream.png' },
{ id: 359, name: 'La Lucky Pickled Ginger Strip', category: 'pickled_fermented_foods', price: 3.99, description: 'Per unit', image: 'cannedimages/La Lucky Pickled Ginger Strip.png' },
{ id: 360, name: 'Nong Phu Pickled Leek in Brine', category: 'pickled_fermented_foods', price: 4.99, description: 'Per unit', image: 'cannedimages/Nong Phu Pickled Leek in Brine.png' },
{ id: 361, name: 'Golden Smell Sugar Scallion in Syrup', category: 'syrup', price: 4.99, description: 'Per unit', image: 'cannedimages/Golden Smell Sugar Scallion in Syrup.png' },
{ id: 362, name: 'TAS Lotus Rootlets in Brine', category: 'pickled_fermented_foods', price: 3.59, description: 'Per unit', image: 'cannedimages/TAS Lotus Rootlets in Brine.png' },
{ id: 363, name: 'Butterfly Brand Pickled Lotus Rootlet', category: 'pickled_fermented_foods', price: 3.99, description: 'Per unit', image: 'cannedimages/Butterfly Brand Pickled Lotus Rootlet.png' },
{ id: 364, name: 'Coconut Tree Pickled Whole Red Chili', category: 'pickled_fermented_foods', price: 4.99, description: 'Per unit', image: 'cannedimages/Coconut Tree Pickled Whole Red Chili.png' },
{ id: 365, name: 'JHC Pickled Whole Red CH', category: 'pickled_fermented_foods', price: 3.99, description: 'Per unit', image: 'cannedimages/JHC Pickled Whole Red CH.png' },
{ id: 366, name: 'Cock Brand Pickled Whole Red Chilli on Vine', category: 'pickled_fermented_foods', price: 3.59, description: 'Per unit', image: 'cannedimages/Cock Brand Pickled Whole Red Chilli on Vine.png' },
{ id: 367, name: 'Chanh Muoi Pickled Lemon in Brine', category: 'pickled_fermented_foods', price: 3.99, description: 'Per unit', image: 'cannedimages/Chanh Muoi Pickled Lemon in Brine.png' },
{ id: 368, name: 'Landsberg White Asparagus', category: 'vegetables', price: 4.99, description: 'Per unit', image: 'cannedimages/Landsberg White Asparagus.png' },
{ id: 369, name: 'Waxberry Canned in Syrup', category: 'fruits', price: 4.99, description: 'Per unit', image: 'cannedimages/Waxberry Canned in Syrup.png' },
{ id: 370, name: 'Florence Coconut Jam', category: 'sweets_desserts', price: 3.99, description: 'Per unit', image: 'cannedimages/Florence Coconut Jam.png' },
{ id: 371, name: 'Florence White Kidney Beans', category: 'legumes_beans', price: 3.99, description: 'Per unit', image: 'cannedimages/Florence White Kidney Beans.png' },
{ id: 372, name: 'Tropica Coconut Jam', category: 'sweets_desserts', price: 4.99, description: 'Per unit', image: 'cannedimages/Tropica Coconut Jam.png' },
{ id: 373, name: 'Honeybee Red Grass Jelly', category: 'sweets_desserts', price: 2.99, description: 'Per unit', image: 'cannedimages/Honeybee Red Grass Jelly.png' },
{ id: 374, name: 'Asian Best Lychee in Syrup', category: 'fruits', price: 3.99, description: 'Per unit', image: 'cannedimages/Asian Best Lychee in Syrup.png' },
{ id: 375, name: 'Asian Best Longan in Syrup', category: 'fruits', price: 3.99, description: 'Per unit', image: 'cannedimages/Asian Best Longan in Syrup.png' },
{ id: 376, name: 'Asian Best Yellow Jackfruit in Syrup', category: 'fruits', price: 2.99, description: 'Per unit', image: 'cannedimages/Asian Best Yellow Jackfruit in Syrup.png' },
{ id: 377, name: 'Pigeon Whole Jackfruits in Syrup', category: 'fruits', price: 3.99, description: 'Per unit', image: 'cannedimages/Pigeon Whole Jackfruits in Syrup.png' },
{ id: 378, name: '999 Baby Bamboo Shoot in Water', category: 'vegetables', price: 2.99, description: 'Per unit', image: 'cannedimages/999 Baby Bamboo Shoot in Water.png' },
{ id: 379, name: '999 Baby Bamboo Shoot in Water', category: 'vegetables', price: 4.99, description: 'Per unit', image: 'cannedimages/999 Baby Bamboo Shoot in Water 4.99.png' },
{ id: 380, name: '999 Bamboo Shoot Tips', category: 'vegetables', price: 3.99, description: 'Per unit', image: 'cannedimages/999 Bamboo Shoot Tips.png' },
{ id: 381, name: 'LA Lucky Banana Blossom in Brine', category: 'pickled_fermented_foods', price: 2.99, description: 'Per unit', image: 'cannedimages/LA Lucky Banana Blossom in Brine.png' },
{ id: 382, name: 'Chaokoh JackFruit in Syrup', category: 'fruits', price: 3.59, description: 'Per unit', image: 'cannedimages/Chaokoh JackFruit in Syrup.png' },
{ id: 383, name: 'Bamboo Garden Slender Bamboo Shoots', category: 'vegetables', price: 2.99, description: 'Per unit', image: 'cannedimages/Bamboo Garden Slender Bamboo Shoots.png' },
{ id: 384, name: 'Aroy - D Coconut Milk', category: 'dairy', price: 12.99, description: 'Per unit', image: 'cannedimages/Aroy - D Coconut Milk.png' },
{ id: 385, name: 'Yeo’s Kaya Coconut Spread', category: 'sweets_desserts', price: 5.99, description: 'Per unit', image: 'cannedimages/Yeo’s Kaya Coconut Spread.png' },
{ id: 386, name: 'TAS Pure Coconut Oil', category: 'oils_extracts', price: 15.90, description: 'Per unit', image: 'cannedimages/TAS Pure Coconut Oil.png' },
{ id: 387, name: 'Nong Phu Cu Kieu Pickled Leek in Brine', category: 'pickled_fermented_foods', price: 7.99, description: 'Per unit', image: 'cannedimages/Nong Phu Cu Kieu Pickled Leek in Brine.png' },
{ id: 388, name: 'Trang Lotus Rootlets in Brine', category: 'pickled_fermented_foods', price: 4.99, description: 'Per unit', image: 'cannedimages/Trang Lotus Rootlets in Brine.png' },
{ id: 389, name: 'Slam Select Sweet & Sour Pickled Lotus Root', category: 'pickled_fermented_foods', price: 4.99, description: 'Per unit', image: 'cannedimages/Slam Select Sweet & Sour Pickled Lotus Root.png' },
{ id: 390, name: 'Slam Select Pickled Lotus Root in Brine', category: 'pickled_fermented_foods', price: 4.99, description: 'Per unit', image: 'cannedimages/Slam Select Pickled Lotus Root in Brine.png' },
{ id: 391, name: 'Asuka Brand Lotus Rootlets in Brine', category: 'pickled_fermented_foods', price: 5.99, description: 'Per unit', image: 'cannedimages/Asuka Brand Lotus Rootlets in Brine.png' },
{ id: 392, name: 'TAS Lotus Stalk in Brine', category: 'pickled_fermented_foods', price: 2.99, description: 'Per unit', image: 'cannedimages/TAS Lotus Stalk in Brine.png' },
{ id: 393, name: 'TAS Pickled Banana Blossom', category: 'pickled_fermented_foods', price: 3.49, description: 'Per unit', image: 'cannedimages/TAS Pickled Banana Blossom.png' },
{ id: 394, name: 'DF Pickled Ginger Strip', category: 'pickled_fermented_foods', price: 5.00, description: 'Per unit', image: 'cannedimages/DF Pickled Ginger Strip.png' },
{ id: 395, name: 'Pantai Laos Style Bamboo Shoot', category: 'vegetables', price: 6.99, description: 'Per unit', image: 'cannedimages/Pantai Laos Style Bamboo Shoot.png' },
{ id: 396, name: 'Dragonfly Oyster Mushroom Curry', category: 'vegetables', price: 8.99, description: 'Per unit', image: 'cannedimages/Dragonfly Oyster Mushroom Curry.png' },
{ id: 397, name: 'Pantai Bamboo Shoot Sliced with Bai Yanan', category: 'vegetables', price: 6.99, description: 'Per unit', image: 'cannedimages/Pantai Bamboo Shoot Sliced with Bai Yanan.png' },
{ id: 398, name: 'TAS Pickled Garlic', category: 'pickled_fermented_foods', price: 5.90, description: 'Per unit', image: 'cannedimages/TAS Pickled Garlic.png' },
{ id: 399, name: 'Tropica Purple Yam Jam', category: 'sweets_desserts', price: 9.99, description: 'Per unit', image: 'cannedimages/Tropica Purple Yam Jam.png' },
{ id: 400, name: 'Florence Jackfruit in Syrup', category: 'fruits', price: 4.99, description: 'Per unit', image: 'cannedimages/Florence Jackfruit in Syrup.png' },
{ id: 401, name: 'Florence ChickPeas in Syrup', category: 'legumes_beans', price: 3.99, description: 'Per unit', image: 'cannedimages/Florence ChickPeas in Syrup.png' },
{ id: 402, name: 'Chef’s Choice Pomelo in Syrup', category: 'fruits', price: 4.99, description: 'Per unit', image: 'cannedimages/Chef’s Choice Pomelo in Syrup.png' },
{ id: 403, name: 'Chaokoh Quail Egg in Brine', category: 'eggs', price: 3.59, description: 'Per unit', image: 'cannedimages/Chaokoh Quail Egg in Brine.png' },
{ id: 404, name: 'Aroy - D Quail Eggs in Water', category: 'eggs', price: 3.59, description: 'Per unit', image: 'cannedimages/Aroy - D Quail Eggs in Water.png' },
{ id: 405, name: 'Asian Best Quail Egg in Water', category: 'eggs', price: 3.59, description: 'Per unit', image: 'cannedimages/Asian Best Quail Egg in Water.png' },
{ id: 406, name: 'O - Cha Sour Bamboo Shoots', category: 'vegetables', price: 6.99, description: 'Per unit', image: 'cannedimages/O - Cha Sour Bamboo Shoots.png' },
{ id: 407, name: 'TAS Sour Sliced Bamboo Shoot', category: 'vegetables', price: 5.99, description: 'Per unit', image: 'cannedimages/TAS Sour Sliced Bamboo Shoot.png' },
{ id: 408, name: 'Elephant Sour Bamboo Shoot Sliced', category: 'vegetables', price: 3.99, description: 'Per unit', image: 'cannedimages/Elephant Sour Bamboo Shoot Sliced.png' },
{ id: 409, name: 'Chaokoh Bamboo Shoots in Water', category: 'vegetables', price: 2.99, description: 'Per unit', image: 'cannedimages/Chaokoh Bamboo Shoots in Water.png' },
{ id: 410, name: 'Mang Tay Lon Asparagus White Peeled', category: 'vegetables', price: 4.99, description: 'Per unit', image: 'cannedimages/Mang Tay Lon Asparagus White Peeled.png' },
{ id: 411, name: 'Three Deer Brand Asparagus Whole Peeled', category: 'vegetables', price: 4.99, description: 'Per unit', image: 'cannedimages/Three Deer Brand Asparagus Whole Peeled.png' },
{ id: 412, name: 'Chaokoh Coconut Milk', category: 'dairy_creamers', price: 12.99, description: 'Per unit', image: 'cannedimages/Chaokoh Coconut Milk.png' },
{ id: 413, name: 'CAF Pickled Olives in Brine', category: 'pickled_fermented_foods', price: 7.99, description: 'Per unit', image: 'cannedimages/CAF Pickled Olives in Brine.png' },
{ id: 414, name: 'Pantai Sliced Bamboo Shoot in Bai Yanang Juice', category: 'vegetables', price: 6.99, description: 'Per unit', image: 'cannedimages/Pantai Sliced Bamboo Shoot in Bai Yanang Juice.png' },
{ id: 415, name: 'Nong Phu Pickled Olives', category: 'pickled_fermented_foods', price: 6.99, description: 'Per unit', image: 'cannedimages/Nong Phu Pickled Olives.png' },
{ id: 416, name: 'Chanh Muoi Pickled Lemon', category: 'pickled_fermented_foods', price: 8.99, description: 'Per unit', image: 'cannedimages/Chanh Muoi Pickled Lemon.png' },
{ id: 417, name: 'Pickled Baby Ambarella', category: 'pickled_fermented_foods', price: 9.00, description: 'Per unit', image: 'cannedimages/Pickled Baby Ambarella.png' },
{ id: 418, name: 'Nong Phu Pickled Mango', category: 'pickled_fermented_foods', price: 6.99, description: 'Per unit', image: 'cannedimages/Nong Phu Pickled Mango.png' },
{ id: 419, name: 'Pickled Young Tamarind Leaf', category: 'pickled_fermented_foods', price: 4.99, description: 'Per unit', image: 'cannedimages/Pickled Young Tamarind Leaf.png' },
{ id: 420, name: 'Millet Chili in Brine', category: 'pickled_fermented_foods', price: 7.99, description: 'Per unit', image: 'cannedimages/Millet Chili in Brine.png' },
{ id: 421, name: 'TAS Coconut Gel in Syrup', category: 'sweets_desserts', price: 5.99, description: 'Per unit', image: 'cannedimages/TAS Coconut Gel in Syrup.png' },
{ id: 422, name: 'TAS Coconut Gel Original in Syrup', category: 'sweets_desserts', price: 5.99, description: 'Per unit', image: 'cannedimages/TAS Coconut Gel Original in Syrup.png' },
{ id: 423, name: 'DragonFly Fruit Mix in Syrup', category: 'fruits', price: 7.50, description: 'Per unit', image: 'cannedimages/DragonFly Fruit Mix in Syrup.png' },
{ id: 424, name: 'TAS Coconut Gel in Syrup Pandan', category: 'sweets_desserts', price: 5.99, description: 'Per unit', image: 'cannedimages/TAS Coconut Gel in Syrup Pandan.png' },
{ id: 425, name: 'Nong Phu Pickled Leek in Brine', category: 'pickled_fermented_foods', price: 7.99, description: 'Per unit', image: 'cannedimages/Nong Phu Pickled Leek in Brine.png' },
{ id: 426, name: 'Dragonfly 3 Taste Sour Bamboo', category: 'vegetables', price: 7.99, description: 'Per unit', image: 'cannedimages/Dragonfly 3 Taste Sour Bamboo.png' },
{ id: 427, name: 'Khamphour Sator in Brine', category: 'pickled_fermented_foods', price: 8.90, description: 'Per unit', image: 'cannedimages/Khamphour Sator in Brine.png' },
{ id: 428, name: 'Dragonfly Pickled Sour Mango', category: 'pickled_fermented_foods', price: 5.99, description: 'Per unit', image: 'cannedimages/Dragonfly Pickled Sour Mango.png' },
{ id: 429, name: 'CAF Sweet Sour Mango', category: 'pickled_fermented_foods', price: 6.99, description: 'Per unit', image: 'cannedimages/CAF Sweet Sour Mango.png' },
{ id: 430, name: 'Asian Best Stripped Bamboo Shoots in Water', category: 'vegetables', price: 9.99, description: 'Per unit', image: 'cannedimages/Asian Best Stripped Bamboo Shoots in Water.png' },
{ id: 431, name: 'Wei Chuan Sliced Water Chestnuts', category: 'vegetables', price: 7.99, description: 'Per unit', image: 'cannedimages/Wei Chuan Sliced Water Chestnuts.png' },
{ id: 432, name: 'Hunsty Pineapple Chunks in Heavy Syrup', category: 'fruits', price: 9.99, description: 'Per unit', image: 'cannedimages/Hunsty Pineapple Chunks in Heavy Syrup.png' },
{ id: 433, name: 'Sun Voi Sour Bamboo Shoot', category: 'vegetables', price: 7.99, description: 'Per unit', image: 'cannedimages/Sun Voi Sour Bamboo Shoot.png' },
{ id: 434, name: 'TAS Spiced Sour Sliced Bamboo Shoot', category: 'vegetables', price: 12.99, description: 'Per unit', image: 'cannedimages/TAS Spiced Sour Sliced Bamboo Shoot.png' },
{ id: 435, name: 'Elephant Sour Bamboo Shoot Sliced', category: 'vegetables', price: 6.99, description: 'Per unit', image: 'cannedimages/Elephant Sour Bamboo Shoot Sliced.png' }










        
    ];
    
    products.forEach(product => {
        console.log(`<div class="product">
            <img src="${product.image}" alt="${product.name}">
            <h2>${product.name}</h2>
            <p>Price: $${product.price.toFixed(2)}</p>
        </div>`);
    });
    

// Function to display products with description and price
function displayProducts(productsToDisplay) {
    const productList = document.getElementById('product-list');
    productList.innerHTML = ''; // Clear previous products
    productsToDisplay.forEach(product => {
        const productDiv = document.createElement('div');
        productDiv.classList.add('product-item');
        productDiv.innerHTML = `
              <img src="${product.image}" alt="${product.name}">
            <h4>${product.name}</h4>
            <p class="price">$${product.price.toFixed(2)}</p>
            <p class="description">${product.description}</p>
            
        `;
        productList.appendChild(productDiv);
    });
}

// Initial display of all products
displayProducts(products);

// Price Label Update
function updatePriceLabel(value) {
    document.getElementById('price-label').textContent = `$${value}`;
}

// Filter Functionality
document.getElementById('price-range').addEventListener('input', function() {
    filterProducts();
});

document.getElementById('category-filter').addEventListener('change', function() {
    filterProducts();
});

// Filtering products by price and category
function filterProducts() {
    const priceLimit = parseFloat(document.getElementById('price-range').value);
    const selectedCategory = document.getElementById('category-filter').value;

    const filteredProducts = products.filter(product => {
        const priceMatch = product.price <= priceLimit;
        const categoryMatch = selectedCategory === 'all' || product.category === selectedCategory;
        return priceMatch && categoryMatch;
    });

    displayProducts(filteredProducts); // Display filtered products
}
