// Sample product data for Sauces section
const products = [
    { id: 1, name: 'Kimlan No Gmo Select Soy Sauce', category: 'soy-sauce', price: 3.50, image: 'sauceimages/KimlanNoGmoSelectSoySauce.png', description: '500ml bottle' },
    { id: 2, name: 'Assi Less Sodium Soy Sauce', category: 'soy-sauce', price: 4.99, image: 'sauceimages/AssiLessSodiumSoySauce.png', description: '500ml bottle' },
    { id: 3, name: 'Tropica Bagoong Round Scad Fish Sauce', category: 'fish-sauce', price: 5.99, image: 'sauceimages/TropicaBagoongRoundScadFishSauce.png', description: '1L bottle' },
    { id: 4, name: 'Kikkoman Smooth Aromatic Soy Sauce', category: 'soy-sauce', price: 4.49, image: 'sauceimages/KikkomanSmoothAromaticSoySauce.png', description: '500ml bottle' },
    { id: 5, name: 'Maggi Savor Chilimansi Liquid Seasoning', category: 'seasoning', price: 2.99, image: 'sauceimages/MaggiSavorChilimansiLiquidSeasoning.png', description: '300ml bottle' },
    { id: 6, name: 'Sichuan Pepper Oil', category: 'oil', price: 3.99, image: 'sauceimages/SichuanPepperOil.png', description: '250ml bottle' },
    { id: 7, name: 'Gemchoice Baizhuozhi', category: 'sauce', price: 5.50, image: 'sauceimages/GemchoiceBaizhuozhi.png', description: '200g jar' },
    { id: 8, name: 'Por Kwan Pad Thai Sauce', category: 'sauce', price: 4.99, image: 'sauceimages/PorKwanPadThaiSauce.png', description: '300ml bottle' },
    { id: 9, name: 'Superior Light Soy Sauce', category: 'soy-sauce', price: 3.50, image: 'sauceimages/SuperiorLightSoySauce.png', description: '500ml bottle' },
    { id: 10, name: 'CJ Foods Korean Bulgogi BBQ Sauce', category: 'sauce', price: 5.99, image: 'sauceimages/CJFoodsKoreanBulgogiBBQSauce.png', description: '350ml bottle' },
    { id: 11, name: 'Marukan Yellow Rice Vinegar', category: 'vinegar', price: 2.99, image: 'sauceimages/MarukanYellowRiceVinegar.png', description: '500ml bottle' },
    { id: 12, name: 'Tuong Viet Hoa Sen Vegan Sauce', category: 'sauce', price: 4.49, image: 'sauceimages/TuongVietHoaSenVeganSauce.png', description: '350ml bottle' },
    { id: 13, name: 'Shirakiku Gochujang Korean Hot Sauce', category: 'hot-sauce', price: 4.99, image: 'sauceimages/ShirakikuGochujangKoreanHotSauce.png', description: '250g jar' },
    { id: 14, name: 'Pantai Mam Nem Fish Sauce', category: 'fish-sauce', price: 3.99, image: 'sauceimages/PantaiMamNemFishSauce.png', description: '500ml bottle' },
    { id: 15, name: 'Kikkoman Mirin Sweet Cooking Seasoning', category: 'sauce', price: 5.49, image: 'sauceimages/KikkomanMirinSweetCookingSeasoning.png', description: '500ml bottle' },
    { id: 16, name: 'Marukan Yuzu Citrus Ponzu Soy Dressing', category: 'sauce', price: 4.49, image: 'sauceimages/MarukanYuzuCitrusPonzuSoyDressing.png', description: '300ml bottle' },
    { id: 17, name: 'Datu Puti Spiced Cane Vinegar', category: 'vinegar', price: 2.79, image: 'sauceimages/DatuPutiSpicedCaneVinegar.png', description: '500ml bottle' },
    { id: 18, name: 'Three Crab Fish Sauce', category: 'fish-sauce', price: 5.29, image: 'sauceimages/ThreeCrabFishSauce.png', description: '1L bottle' },
    { id: 19, name: 'Kikkoman Sushi Sauce', category: 'sauce', price: 3.99, image: 'sauceimages/KikkomanSushiSauce.png', description: '250ml bottle' },
    { id: 20, name: 'Marca Pina Spiced Coconut Vinegar', category: 'vinegar', price: 3.50, image: 'sauceimages/MarcaPinaSpicedCoconutVinegar.png', description: '500ml bottle' },
    { id: 21, name: 'Samyang Buldak Hot Sauce', category: 'hot-sauce', price: 4.99, image: 'sauceimages/SamyangBuldakHotSauce.png', description: '200g bottle' },
    { id: 22, name: 'Mizkan Grain Flavored Distilled Vinegar', category: 'vinegar', price: 3.99, image: 'sauceimages/MizkanGrainFlavoredDistilledVinegar.png', description: '500ml bottle' },
    { id: 23, name: 'Sunnyside Cincalok Pickled Shrimp Sauce', category: 'sauce', price: 2.99, image: 'sauceimages/SunnysideCincalokPickledShrimpSauce.png', description: '200g jar' },
    { id: 24, name: 'Pearl River Bridge Golden Label Superior Light Soy Sauce', category: 'soy-sauce', price: 4.49, image: 'sauceimages/PearlRiverBridgeGoldenLabelSuperiorLightSoySauce.png', description: '500ml bottle' },
    { id: 25, name: 'Canola Olive Oil', category: 'oil', price: 5.99, image: 'sauceimages/CanolaOliveOil.png', description: '1L bottle' },
    { id: 26, name: 'Pantai Vietnam Rice Paper Sauce', category: 'sauce', price: 3.49, image: 'sauceimages/PantaiVietnamRicePaperSauce.png', description: '200ml bottle' },
    { id: 27, name: 'Mam Nem Phan Thiet Fish Sauce', category: 'fish-sauce', price: 3.99, image: 'sauceimages/MamNemPhanThietFishSauce.png', description: '500ml bottle' },
    { id: 28, name: 'Chu Bang Peanut Oil', category: 'oil', price: 5.50, image: 'sauceimages/ChuBangPeanutOil.png', description: '500ml bottle' },
    { id: 29, name: 'Shirakiku Teriyaki Sauce', category: 'sauce', price: 4.99, image: 'sauceimages/ShirakikuTeriyakiSauce.png', description: '300ml bottle' },
    { id: 30, name: 'Daisho Yakinikuno Tare Yuzi', category: 'sauce', price: 3.99, image: 'sauceimages/DaishoYakinikunoTareYuzi.png', description: '250ml bottle' },
    { id: 31, name: 'Lee Kum Kee Garlic Hoisin Sauce', category: 'sauce', price: 5.99, image: 'sauceimages/LeeKumKeeGarlicHoisinSauce.png', description: '350ml bottle' },
    { id: 32, name: 'Megachef Seasoned Fish Sauce', category: 'fish-sauce', price: 5.49, image: 'sauceimages/MegachefSeasonedFishSauce.png', description: '500ml bottle' },
    { id: 33, name: 'Amoy Lo Sui Marinade Sauce', category: 'sauce', price: 3.99, image: 'sauceimages/AmoyLoSuiMarinadeSauce.png', description: '250ml bottle' },
    { id: 34, name: 'Lee Kum Kee Hot Blended Sesame Oil', category: 'oil', price: 5.29, image: 'sauceimages/LeeKumKeeHotBlendedSesameOil.png', description: '250ml bottle' },
    { id: 35, name: 'NSS Japanese Sesame Flavored Oil', category: 'oil', price: 5.99, image: 'sauceimages/NSSJapaneseSesameFlavoredOil.png', description: '250ml bottle' },
    { id: 36, name: 'Wang Korea 100% Sesame Oil', category: 'oil', price: 6.49, image: 'sauceimages/WangKorea100%SesameOil.png', description: '500ml bottle' },
    { id: 37, name: 'Pantai Orange Sauce', category: 'sauce', price: 3.79, image: 'sauceimages/PantaiOrangeSauce.png', description: '250ml bottle' },
    { id: 38, name: 'Kadoya Sesame Oil', category: 'oil', price: 6.99, image: 'sauceimages/KadoyaSesameOil.png', description: '500ml bottle' },
    { id: 39, name: 'Kimlan Soy Paste', category: 'paste', price: 3.99, image: 'sauceimages/KimlanSoyPaste.png', description: '200g jar' },
    { id: 40, name: 'Kikkoman Tempura Dipping Sauce', category: 'sauce', price: 4.29, image: 'sauceimages/KikkomanTempuraDippingSauce.png', description: '300ml bottle' },
    { id: 41, name: 'Kikkoman Gluten Free Sweet Chilli Sauce', category: 'sauce', price: 4.50, image: 'sauceimages/KikkomanGlutenFreeSweetChilliSauce.png', description: '250ml bottle' },
    { id: 42, name: 'Lee Kum Kee Hoisin Sauce', category: 'sauce', price: 4.99, image: 'sauceimages/LeeKumKeeHoisinSauce.png', description: '300ml bottle' },
    { id: 43, name: 'Kamayan Sweet Shrimp Paste', category: 'sauce', price: 3.99, image: 'sauceimages/KamayanSweetShrimpPaste.png', description: '250g jar' },
    { id: 44, name: 'Megachef Premium Mushroom Sauce', category: 'sauce', price: 5.49, image: 'sauceimages/MegachefPremiumMushroomSauce.png', description: '350ml bottle' },
    { id: 45, name: 'Silver Swan Coconut Vinegar', category: 'vinegar', price: 2.99, image: 'sauceimages/SilverSwanCoconutVinegar.png', description: '500ml bottle' },
    { id: 46, name: 'Kadoya 100% Pure Sesame Oil', category: 'oil', price: 6.49, image: 'sauceimages/Kadoya100%PureSesameOil.png', description: '500ml bottle' },
    { id: 47, name: 'J - Basket Teriyaki Sauce & Marinade Original', category: 'sauce', price: 4.99, image: 'sauceimages/J-BasketTeriyakiSauce&MarinadeOriginal.png', description: '300ml bottle' },
    { id: 48, name: 'Chin Su Fish Sauce', category: 'fish-sauce', price: 3.99, image: 'sauceimages/ChinSuFishSauce.png', description: '500ml bottle' },
    { id: 49, name: 'Pantai Sweet Soy Sauce', category: 'soy-sauce', price: 3.49, image: 'sauceimages/PantaiSweetSoySauce.png', description: '250ml bottle' },
    { id: 50, name: 'Lee Kum Kee Abalone Sauce', category: 'sauce', price: 6.99, image: 'sauceimages/LeeKumKeeAbaloneSauce.png', description: '300ml bottle' },
    { id: 51, name: 'Yamasa Sashimi Soy Sauce', category: 'soy-sauce', price: 5.99, image: 'sauceimages/YamasaSashimiSoySauce.png', description: '500ml bottle' },
    { id: 52, name: 'Anh Hong Mam Nem Pha San', category: 'fish-sauce', price: 4.49, image: 'sauceimages/AnhHongMamNemPhaSan.png', description: '500ml bottle' },
    { id: 53, name: 'Chin Su Soy Sauce Nuoc Tuong', category: 'soy-sauce', price: 3.99, image: 'sauceimages/ChinSuSoySauceNuocTuong.png', description: '500ml bottle' },
    { id: 54, name: 'Pantai Chicken Rice Sauce', category: 'sauce', price: 2.99, image: 'sauceimages/PantaiChickenRiceSauce.png', description: '200ml bottle' },
    { id: 55, name: 'Nong Phu Mam Nem Xay Fish Sauce', category: 'fish-sauce', price: 3.49, image: 'sauceimages/NongPhuMamNemXayFishSauce.png', description: '500ml bottle' },
    { id: 56, name: 'Wan Ja Shan Tamari Soy Sauce', category: 'soy-sauce', price: 5.99, image: 'sauceimages/WanJaShanTamariSoySauce.png', description: '500ml bottle' },
    { id: 57, name: 'Kikkoman Somen Tsuyu Sauce Base', category: 'sauce', price: 4.99, image: 'sauceimages/KikkomanSomenTsuyuSauceBase.png', description: '300ml bottle' },
    { id: 58, name: 'Kikkoman Gluten Free Soy Sauce', category: 'soy-sauce', price: 6.49, image: 'sauceimages/KikkomanGlutenFreeSoySauce.png', description: '500ml bottle' },
    { id: 59, name: 'Shinho Superfine Soy Sauce', category: 'soy-sauce', price: 4.29, image: 'sauceimages/ShinhoSuperfineSoySauce.png', description: '500ml bottle' },
    { id: 60, name: '40N Tin Fish Sauce', category: 'fish-sauce', price: 3.99, image: 'sauceimages/40NTinFishSauce.png', description: '500ml tin' },
    { id: 61, name: 'Lee Kum Kee Original Stir-Fry Sauce', category: 'sauce', price: 4.49, image: 'sauceimages/LeeKumKeeOriginalStir-FrySauce.png', description: '300ml bottle' },
    { id: 62, name: 'Nong Phu Mam Nem Phu Quoc Fish Sauce', category: 'fish-sauce', price: 4.99, image: 'sauceimages/NongPhuMamNemPhuQuocFishSauce.png', description: '500ml bottle' },
    { id: 63, name: 'Kikkoman Sushi & Sashimi Soy Sauce', category: 'soy-sauce', price: 5.99, image: 'sauceimages/KikkomanSushi&SashimiSoySauce.png', description: '500ml bottle' },
    { id: 64, name: 'Haday Seafood Flavored Soy Sauce', category: 'soy-sauce', price: 4.29, image: 'sauceimages/HadaySeafoodFlavoredSoySauce.png', description: '500ml bottle' },
    { id: 65, name: 'Lee Kum Kee Black Bean Sauce', category: 'sauce', price: 5.50, image: 'sauceimages/LeeKumKeeBlackBeanSauce.png', description: '300ml bottle' },
    { id: 66, name: 'Mizkan Sesame Flavored Dressing', category: 'dressing', price: 3.79, image: 'sauceimages/MizkanSesameFlavoredDressing.png', description: '250ml bottle' },
    { id: 67, name: 'Longevity Peanut Oil Blend', category: 'oil', price: 6.29, image: 'sauceimages/LongevityPeanutOilBlend.png', description: '500ml bottle' },
    { id: 68, name: 'Lee Vietnamese Spring Roll Sauce', category: 'sauce', price: 2.99, image: 'sauceimages/LeeVietnameseSpringRollSauce.png', description: '200ml bottle' },
    { id: 69, name: 'Kikkoman Organic Soy Sauce', category: 'soy-sauce', price: 6.99, image: 'sauceimages/KikkomanOrganicSoySauce.png', description: '500ml bottle' },
    { id: 70, name: 'Sukina Teriyaki Sauce', category: 'sauce', price: 4.29, image: 'sauceimages/SukinaTeriyakiSauce.png', description: '300ml bottle' },
    { id: 71, name: 'Kikkoman Salad Rice Vinegar', category: 'vinegar', price: 3.99, image: 'sauceimages/KikkomanSaladRiceVinegar.png', description: '500ml bottle' },
    { id: 72, name: 'Lee Kum Kee Premium Old Oyster Saucer', category: 'sauce', price: 6.49, image: 'sauceimages/LeeKumKeePremiumOldOysterSaucer.png', description: '250ml bottle' },
    { id: 73, name: 'Nam Pla Oyster Fish Sauce', category: 'fish-sauce', price: 3.49, image: 'sauceimages/NamPlaOysterFIshSauce.png', description: '500ml bottle' },
    { id: 74, name: 'Kewpie Wafu Dressing', category: 'dressing', price: 3.99, image: 'sauceimages/KewpieWafuDressing.png', description: '250ml bottle' },
    { id: 75, name: 'Mam Nem Pha San Fish Sauce', category: 'fish-sauce', price: 4.99, image: 'sauceimages/MamNemPhaSanFishSauce.png', description: '500ml bottle' },
    { id: 76, name: 'Saigon Fish Sauce', category: 'fish-sauce', price: 3.79, image: 'sauceimages/SaigonFishSauce.png', description: '500ml bottle' },
    { id: 77, name: 'Datu Puti Sukang Sugarcane Vinegar', category: 'vinegar', price: 2.99, image: 'sauceimages/DatuPutiSukangSugarcaneVinegar.png', description: '500ml bottle' },
    { id: 78, name: 'Kikkoman Sweet & Sour Sauce', category: 'sauce', price: 4.29, image: 'sauceimages/KikkomanSweet&SourSauce.png', description: '300ml bottle' },
    { id: 79, name: 'J - Basket Creamy Miso Dressing', category: 'dressing', price: 3.49, image: 'sauceimages/J-BasketCreamyMisoDressing.png', description: '250ml bottle' },
    { id: 80, name: 'Wan Ja Shan Organic Gluten Free Tamari Soy Sauce', category: 'soy-sauce', price: 7.99, image: 'sauceimages/WanJaShanOrganicGlutenFreeTamariSoySauce.png', description: '500ml bottle' },
    { id: 81, name: 'Mizkan Jun Genmai Su Vinegar', category: 'vinegar', price: 4.29, image: 'sauceimages/MizkanJunGenmaiSuVinegar.png', description: '500ml bottle' },
    { id: 82, name: 'Kikkoman Black Bean Sauce with Garlic', category: 'sauce', price: 5.99, image: 'sauceimages/KikkomanBlackBeanSaucewithGarlic.png', description: '300ml bottle' },
    { id: 83, name: 'Con Gau Nuoc Tuong Soy Sauce', category: 'soy-sauce', price: 4.79, image: 'sauceimages/ConGauNuocTuongSoySauce.png', description: '500ml bottle' },
    { id: 84, name: 'Roxy Canola Olive Blended Oil', category: 'oil', price: 5.50, image: 'sauceimages/RoxyCanolaOliveBlendedOil.png', description: '1L bottle' },
    { id: 85, name: 'Pearl River Superior Light Soy Sauce', category: 'soy-sauce', price: 4.99, image: 'sauceimages/PearlRiverSuperiorLightSoySauce.png', description: '500ml bottle' },
    { id: 86, name: 'Haday Signature Oyster Flavored Sauce', category: 'sauce', price: 4.29, image: 'sauceimages/HadaySignatureOysterFlavoredSauce.png', description: '300ml bottle' },
    { id: 87, name: 'Kikkoman Gluten Free Tamari Soy Sauce', category: 'soy-sauce', price: 5.99, image: 'sauceimages/KikkomanGlutenFreeTamariSoySauce.png', description: '500ml bottle' },
    { id: 88, name: 'Dynasty Chinese Duck Sauce', category: 'sauce', price: 3.99, image: 'sauceimages/DynastyChineseDuckSauce.png', description: '250ml bottle' },
    { id: 89, name: 'Red Boat Special Batch Fish Sauce', category: 'fish-sauce', price: 5.99, image: 'sauceimages/RedBoatSpecialBatchFishSauce.png', description: '500ml bottle' },
    { id: 90, name: 'Phu Quoc Fish Sauce', category: 'fish-sauce', price: 4.49, image: 'sauceimages/PhuQuocFishSauce.png', description: '500ml bottle' },
    { id: 91, name: 'Marukan Ponzu Premium Soy Dressing with Sudachi Citrus', category: 'dressing', price: 4.99, image: 'sauceimages/MarukanPonzuPremiumSoyDressingwithSudachiCitrus.png', description: '300ml bottle' },
    { id: 92, name: 'Wei Chuan Spicy Dumpling Sauce', category: 'sauce', price: 3.99, image: 'sauceimages/WeiChuanSpicyDumplingSauce.png', description: '250ml bottle' },
    { id: 92, name: 'Lee Oyster Sauce', category: 'sauce', price: 3.99, image: 'sauceimages/LeeOysterSauce.png', description: '300ml bottle' },
    { id: 93, name: 'Megachef Premium Oyster Flavored Sauce', category: 'sauce', price: 4.99, image: 'sauceimages/MegachefPremiumOysterFlavoredSauce.png', description: '350ml bottle' },
    { id: 94, name: 'Chin Su Nam Ngu Fish Sauce', category: 'fish-sauce', price: 3.99, image: 'sauceimages/ChinSuNamNguFishSauce.png', description: '500ml bottle' },
    { id: 95, name: 'Large Lotte Cooking Wine', category: 'wine', price: 5.49, image: 'sauceimages/LargeLotteCookingWine.png', description: '750ml bottle' },
    { id: 96, name: 'Wan Ja Shan Sashimi Soy Sauce', category: 'soy-sauce', price: 5.99, image: 'sauceimages/WanJaShanSashimiSoySauce.png', description: '500ml bottle' },
    { id: 97, name: 'Kikkoman Stir Fry Sauce', category: 'sauce', price: 4.49, image: 'sauceimages/KikkomanStirFrySauce.png', description: '250ml bottle' },
    { id: 98, name: 'Amoy Seafood Soy Sauce', category: 'soy-sauce', price: 4.29, image: 'sauceimages/AmoySeafoodSoySauce.png', description: '500ml bottle' },
    { id: 99, name: 'AAA Grade Sai Tan Fish Sauce', category: 'fish-sauce', price: 4.99, image: 'sauceimages/AAAGradeSaiTanFishSauce.png', description: '500ml bottle' },
    { id: 100, name: 'Marca Pina Soy Sauce', category: 'soy-sauce', price: 3.79, image: 'sauceimages/MarcaPinaSoySauce.png', description: '500ml bottle' },
    { id: 101, name: 'Lee Kum Kee Premium Soy Sauce', category: 'soy-sauce', price: 5.99, image: 'sauceimages/LeeKumKeePremiumSoySauce.png', description: '500ml bottle' },
    { id: 102, name: 'Pearl River Bridge Mushroom Flavored Dark Soy Sauce', category: 'soy-sauce', price: 4.49, image: 'sauceimages/PearlRiverBridgeMushroomFlavoredDarkSoySauce.png', description: '500ml bottle' },
    { id: 103, name: 'Squid Fish Sauce', category: 'fish-sauce', price: 3.99, image: 'sauceimages/SquidFishSauce.png', description: '500ml bottle' },
    { id: 104, name: 'Wan Ja Shan Bonito Soy Sauce', category: 'soy-sauce', price: 4.99, image: 'sauceimages/WanJaShanBonitoSoySauce.png', description: '500ml bottle' },
    { id: 105, name: 'Super Q Vegetarian Soy Sauce', category: 'soy-sauce', price: 3.79, image: 'sauceimages/SuperQVegetarianSoySauce.png', description: '500ml bottle' },
    { id: 106, name: 'Kikkoman Tamari Soy Sauce', category: 'soy-sauce', price: 5.99, image: 'sauceimages/KikkomanTamariSoySauce.png', description: '500ml bottle' },
    { id: 107, name: 'Vegetarian Soya Sauce', category: 'soy-sauce', price: 3.49, image: 'sauceimages/VegetarianSoyaSauce.png', description: '500ml bottle' },
    { id: 108, name: 'Marca Pina Sukang Puti', category: 'vinegar', price: 3.99, image: 'sauceimages/MarcaPinaSukangPuti.png', description: '500ml bottle' },
    { id: 109, name: 'Daisho Japanese Sukiyaki Warishita Hotpot Sauce', category: 'sauce', price: 4.99, image: 'sauceimages/DaishoJapaneseSukiyakiWarishitaHotpotSauce.png', description: '300ml bottle' },
    { id: 110, name: 'Ajinomoto Gyoza Dipping Sauce', category: 'sauce', price: 3.49, image: 'sauceimages/AjinomotoGyozaDippingSauce.png', description: '250ml bottle' },
    { id: 111, name: 'J - Basket Teriyaki Sauce & Marinade Spicy', category: 'sauce', price: 4.99, image: 'sauceimages/J-BasketTeriyakiSauce&MarinadeSpicy.png', description: '300ml bottle' },
    { id: 112, name: 'Tropica Bagoong Terong Boneless', category: 'fish-sauce', price: 3.79, image: 'sauceimages/TropicaBagoongTerongBoneless.png', description: '500g jar' },
    { id: 113, name: 'Kadoya Pure Sesame Oil', category: 'oil', price: 6.99, image: 'sauceimages/KadoyaPureSesameOil.png', description: '500ml bottle' },
    { id: 114, name: 'Pantai Soy Bean Paste', category: 'paste', price: 3.99, image: 'sauceimages/PantaiSoyBeanPaste.png', description: '500g jar' },
    { id: 115, name: 'Three Crabs Fish Sauce', category: 'fish-sauce', price: 4.99, image: 'sauceimages/ThreeCrabsFishSauce.png', description: '500ml bottle' },
    { id: 116, name: 'Lee Kum Kee Seasoned Soy Sauce for Seafood', category: 'soy-sauce', price: 4.79, image: 'sauceimages/LeeKumKeeSeasonedSoySauceforSeafood.png', description: '500ml bottle' },
    { id: 117, name: 'Two Crab Fish Sauce', category: 'fish-sauce', price: 3.99, image: 'sauceimages/TwoCrabFishSauce.png', description: '500ml bottle' },
    { id: 118, name: 'Kikkoman Less Sodium Teriyaki', category: 'sauce', price: 4.29, image: 'sauceimages/KikkomanLessSodiumTeriyaki.png', description: '300ml bottle' },
    { id: 119, name: 'Mam Nem Phu Quoc Special Anchovy Fish Sauce', category: 'fish-sauce', price: 4.49, image: 'sauceimages/MamNemPhuQuocSpecialAnchovyFishSauce.png', description: '500ml bottle' },
    { id: 120, name: 'Asian Taste Corn Oil', category: 'oil', price: 4.99, image: 'sauceimages/AsianTasteCornOil.png', description: '1L bottle' },
    { id: 121, name: 'Maggi Dau Hao Oyster Sauce', category: 'sauce', price: 3.99, image: 'sauceimages/MaggiDauHaoOysterSauce.png', description: '300ml bottle' },
    { id: 122, name: 'Que Huong Fish Sauce', category: 'fish-sauce', price: 4.99, image: 'sauceimages/QueHuongFishSauce.png', description: '500ml bottle' },
    { id: 123, name: 'Red Boat Fish Sauce 40 N', category: 'fish-sauce', price: 5.99, image: 'sauceimages/RedBoatFishSauce40N.png', description: '500ml bottle' },
    { id: 124, name: 'Marukan Sweet and Tangy Rice Vinegar', category: 'vinegar', price: 3.49, image: 'sauceimages/MarukanSweetandTangyRiceVinegar.png', description: '500ml bottle' },
    { id: 125, name: 'Maggi Savor Calamansi Liquid Seasoning', category: 'seasoning', price: 2.99, image: 'sauceimages/MaggiSavorCalamansiLiquidSeasoning.png', description: '300ml bottle' },
    { id: 92, name: 'Lee Oyster Sauce', category: 'sauce', price: 3.99, image: 'sauceimages/LeeOysterSauce.png', description: '300ml bottle' },
    { id: 93, name: 'Megachef Premium Oyster Flavored Sauce', category: 'sauce', price: 4.99, image: 'sauceimages/MegachefPremiumOysterFlavoredSauce.png', description: '350ml bottle' },
    { id: 94, name: 'Chin Su Nam Ngu Fish Sauce', category: 'fish-sauce', price: 3.99, image: 'sauceimages/ChinSuNamNguFishSauce.png', description: '500ml bottle' },
    { id: 95, name: 'Large Lotte Cooking Wine', category: 'wine', price: 5.49, image: 'sauceimages/LargeLotteCookingWine.png', description: '750ml bottle' },
    { id: 96, name: 'Wan Ja Shan Sashimi Soy Sauce', category: 'soy-sauce', price: 5.99, image: 'sauceimages/WanJaShanSashimiSoySauce.png', description: '500ml bottle' },
    { id: 97, name: 'Kikkoman Stir Fry Sauce', category: 'sauce', price: 4.49, image: 'sauceimages/KikkomanStirFrySauce.png', description: '250ml bottle' },
    { id: 98, name: 'Amoy Seafood Soy Sauce', category: 'soy-sauce', price: 4.29, image: 'sauceimages/AmoySeafoodSoySauce.png', description: '500ml bottle' },
    { id: 99, name: 'AAA Grade Sai Tan Fish Sauce', category: 'fish-sauce', price: 4.99, image: 'sauceimages/AAAGradeSaiTanFishSauce.png', description: '500ml bottle' },
    { id: 100, name: 'Marca Pina Soy Sauce', category: 'soy-sauce', price: 3.79, image: 'sauceimages/MarcaPinaSoySauce.png', description: '500ml bottle' },
    { id: 101, name: 'Lee Kum Kee Premium Soy Sauce', category: 'soy-sauce', price: 5.99, image: 'sauceimages/LeeKumKeePremiumSoySauce.png', description: '500ml bottle' },
    { id: 102, name: 'Pearl River Bridge Mushroom Flavored Dark Soy Sauce', category: 'soy-sauce', price: 4.49, image: 'sauceimages/PearlRiverBridgeMushroomFlavoredDarkSoySauce.png', description: '500ml bottle' },
    { id: 103, name: 'Squid Fish Sauce', category: 'fish-sauce', price: 3.99, image: 'sauceimages/SquidFishSauce.png', description: '500ml bottle' },
    { id: 104, name: 'Wan Ja Shan Bonito Soy Sauce', category: 'soy-sauce', price: 4.99, image: 'sauceimages/WanJaShanBonitoSoySauce.png', description: '500ml bottle' },
    { id: 105, name: 'Super Q Vegetarian Soy Sauce', category: 'soy-sauce', price: 3.79, image: 'sauceimages/SuperQVegetarianSoySauce.png', description: '500ml bottle' },
    { id: 106, name: 'Kikkoman Tamari Soy Sauce', category: 'soy-sauce', price: 5.99, image: 'sauceimages/KikkomanTamariSoySauce.png', description: '500ml bottle' },
    { id: 107, name: 'Vegetarian Soya Sauce', category: 'soy-sauce', price: 3.49, image: 'sauceimages/VegetarianSoyaSauce.png', description: '500ml bottle' },
    { id: 108, name: 'Marca Pina Sukang Puti', category: 'vinegar', price: 3.99, image: 'sauceimages/MarcaPinaSukangPuti.png', description: '500ml bottle' },
    { id: 109, name: 'Daisho Japanese Sukiyaki Warishita Hotpot Sauce', category: 'sauce', price: 4.99, image: 'sauceimages/DaishoJapaneseSukiyakiWarishitaHotpotSauce.png', description: '300ml bottle' },
    { id: 110, name: 'Ajinomoto Gyoza Dipping Sauce', category: 'sauce', price: 3.49, image: 'sauceimages/AjinomotoGyozaDippingSauce.png', description: '250ml bottle' },
    { id: 111, name: 'J - Basket Teriyaki Sauce & Marinade Spicy', category: 'sauce', price: 4.99, image: 'sauceimages/J-BasketTeriyakiSauce&MarinadeSpicy.png', description: '300ml bottle' },
    { id: 112, name: 'Tropica Bagoong Terong Boneless', category: 'fish-sauce', price: 3.79, image: 'sauceimages/TropicaBagoongTerongBoneless.png', description: '500g jar' },
    { id: 113, name: 'Kadoya Pure Sesame Oil', category: 'oil', price: 6.99, image: 'sauceimages/KadoyaPureSesameOil.png', description: '500ml bottle' },
    { id: 114, name: 'Pantai Soy Bean Paste', category: 'paste', price: 3.99, image: 'sauceimages/PantaiSoyBeanPaste.png', description: '500g jar' },
    { id: 115, name: 'Three Crabs Fish Sauce', category: 'fish-sauce', price: 4.99, image: 'sauceimages/ThreeCrabsFishSauce.png', description: '500ml bottle' },
    { id: 116, name: 'Lee Kum Kee Seasoned Soy Sauce for Seafood', category: 'soy-sauce', price: 4.79, image: 'sauceimages/LeeKumKeeSeasonedSoySauceforSeafood.png', description: '500ml bottle' },
    { id: 117, name: 'Kimlan No Gmo Select Soy Sauce', category: 'soy-sauce', price: 4.99, image: 'sauceimages/KimlanNoGmoSelectSoySauce.png', description: '500ml bottle' },
    { id: 118, name: 'Assi Less Sodium Soy Sauce', category: 'soy-sauce', price: 3.99, image: 'sauceimages/AssiLessSodiumSoySauce.png', description: '500ml bottle' },
    { id: 119, name: 'Tropica Bagoong Round Scad Fish Sauce', category: 'fish-sauce', price: 3.79, image: 'sauceimages/TropicaBagoongRoundScadFishSauce.png', description: '500ml bottle' },
    { id: 120, name: 'Kikkoman Smooth Aromatic Soy Sauce', category: 'soy-sauce', price: 5.49, image: 'sauceimages/KikkomanSmoothAromaticSoySauce.png', description: '500ml bottle' },
    { id: 121, name: 'Maggi Savor Chilimansi Liquid Seasoning', category: 'seasoning', price: 3.49, image: 'sauceimages/MaggiSavorChilimansiLiquidSeasoning.png', description: '300ml bottle' },
    { id: 122, name: 'Sichuan Pepper Oil', category: 'oil', price: 4.99, image: 'sauceimages/SichuanPepperOil.png', description: '200ml bottle' },
    { id: 123, name: 'Gemchoice Baizhuozhi', category: 'sauce', price: 5.49, image: 'sauceimages/GemchoiceBaizhuozhi.png', description: '200g jar' },
    { id: 124, name: 'Por Kwan Pad Thai Sauce', category: 'sauce', price: 4.99, image: 'sauceimages/PorKwanPadThaiSauce.png', description: '300ml bottle' },
    { id: 125, name: 'Superior Light Soy Sauce', category: 'soy-sauce', price: 4.29, image: 'sauceimages/SuperiorLightSoySauce.png', description: '500ml bottle' },
    { id: 126, name: 'CJ Foods Korean Bulgogi BBQ Sauce', category: 'sauce', price: 5.99, image: 'sauceimages/CJFoodsKoreanBulgogiBBQSauce.png', description: '500ml bottle' },
    { id: 127, name: 'Marukan Yellow Rice Vinegar', category: 'vinegar', price: 3.99, image: 'sauceimages/MarukanYellowRiceVinegar.png', description: '500ml bottle' },
    { id: 128, name: 'Tuong Viet Hoa Sen Vegan Sauce', category: 'sauce', price: 4.49, image: 'sauceimages/TuongVietHoaSenVeganSauce.png', description: '300ml bottle' },
    { id: 129, name: 'Shirakiku Gochujang Korean Hot Sauce', category: 'sauce', price: 4.99, image: 'sauceimages/ShirakikuGochujangKoreanHotSauce.png', description: '200g jar' },
    { id: 130, name: 'Pantai Mam Nem Fish Sauce', category: 'fish-sauce', price: 3.99, image: 'sauceimages/PantaiMamNemFishSauce.png', description: '500ml bottle' },
    { id: 131, name: 'Kikkoman Mirin Sweet Cooking Seasoning', category: 'sauce', price: 5.49, image: 'sauceimages/KikkomanMirinSweetCookingSeasoning.png', description: '500ml bottle' },
    { id: 132, name: 'Marukan Yuzu Citrus Ponzu Soy Dressing', category: 'sauce', price: 4.99, image: 'sauceimages/MarukanYuzuCitrusPonzuSoyDressing.png', description: '500ml bottle' },
    { id: 133, name: 'Datu Puti Spiced Cane Vinegar', category: 'vinegar', price: 3.79, image: 'sauceimages/DatuPutiSpicedCaneVinegar.png', description: '500ml bottle' },
    { id: 134, name: 'Three Crab Fish Sauce', category: 'fish-sauce', price: 3.99, image: 'sauceimages/ThreeCrabFishSauce.png', description: '500ml bottle' },
    { id: 135, name: 'Kikkoman Sushi Sauce', category: 'soy-sauce', price: 4.99, image: 'sauceimages/KikkomanSushiSauce.png', description: '300ml bottle' },
    { id: 136, name: 'Marca Pina Spiced Coconut Vinegar', category: 'vinegar', price: 4.49, image: 'sauceimages/MarcaPinaSpicedCoconutVinegar.png', description: '500ml bottle' },
    { id: 137, name: 'Samyang Buldak Hot Sauce', category: 'sauce', price: 4.29, image: 'sauceimages/SamyangBuldakHotSauce.png', description: '200g bottle' },
    { id: 138, name: 'Mizkan Grain Flavored Distilled Vinegar', category: 'vinegar', price: 2.99, image: 'sauceimages/MizkanGrainFlavoredDistilledVinegar.png', description: '500ml bottle' },
    { id: 139, name: 'Sunnyside Cincalok Pickled Shrimp Sauce', category: 'sauce', price: 3.79, image: 'sauceimages/SunnysideCincalokPickledShrimpSauce.png', description: '200g jar' },
    { id: 140, name: 'Pearl River Bridge Golden Label Superior Light Soy Sauce', category: 'soy-sauce', price: 5.99, image: 'sauceimages/PearlRiverBridgeGoldenLabelSuperiorLightSoySauce.png', description: '500ml bottle' },
    { id: 141, name: 'Canola Olive Oil', category: 'oil', price: 5.99, image: 'sauceimages/CanolaOliveOil.png', description: '500ml bottle' },
    { id: 142, name: 'Pantai Vietnam Rice Paper Sauce', category: 'sauce', price: 4.49, image: 'sauceimages/PantaiVietnamRicePaperSauce.png', description: '300ml bottle' },
    { id: 143, name: 'Mam Nem Phan Thiet Fish Sauce', category: 'fish-sauce', price: 4.29, image: 'sauceimages/MamNemPhanThietFishSauce.png', description: '500ml bottle' },
    { id: 144, name: 'Chu Bang Peanut Oil', category: 'oil', price: 6.49, image: 'sauceimages/ChuBangPeanutOil.png', description: '500ml bottle' },
    { id: 145, name: 'Shirakiku Teriyaki Sauce', category: 'sauce', price: 5.49, image: 'sauceimages/ShirakikuTeriyakiSauce.png', description: '300ml bottle' },
    { id: 146, name: 'Daisho Yakinikuno Tare Yuzi', category: 'sauce', price: 4.99, image: 'sauceimages/DaishoYakinikunoTareYuzi.png', description: '500ml bottle' },
    { id: 147, name: 'Lee Kum Kee Garlic Hoisin Sauce', category: 'sauce', price: 5.49, image: 'sauceimages/LeeKumKeeGarlicHoisinSauce.png', description: '300ml bottle' },
    { id: 148, name: 'Megachef Seasoned Fish Sauce', category: 'fish-sauce', price: 4.99, image: 'sauceimages/MegachefSeasonedFishSauce.png', description: '500ml bottle' },
    { id: 149, name: 'Amoy Lo Sui Marinade Sauce', category: 'sauce', price: 4.29, image: 'sauceimages/AmoyLoSuiMarinadeSauce.png', description: '300ml bottle' },
    { id: 150, name: 'Lee Kum Kee Hot Blended Sesame Oil', category: 'oil', price: 6.99, image: 'sauceimages/LeeKumKeeHotBlendedSesameOil.png', description: '250ml bottle' },
    { id: 151, name: 'NSS Japanese Sesame Flavored Oil', category: 'oil', price: 5.99, image: 'sauceimages/NSSJapaneseSesameFlavoredOil.png', description: '250ml bottle' },
    { id: 152, name: 'Wang Korea 100% Sesame Oil', category: 'oil', price: 6.49, image: 'sauceimages/WangKorea100%SesameOil.png', description: '500ml bottle' },
    { id: 153, name: 'Pantai Orange Sauce', category: 'sauce', price: 3.79, image: 'sauceimages/PantaiOrangeSauce.png', description: '300ml bottle' },
    { id: 154, name: 'Kadoya Sesame Oil', category: 'oil', price: 6.99, image: 'sauceimages/KadoyaSesameOil.png', description: '500ml bottle' },
    { id: 155, name: 'Kimlan Soy Paste', category: 'paste', price: 4.29, image: 'sauceimages/KimlanSoyPaste.png', description: '500g jar' },
    { id: 156, name: 'Kikkoman Tempura Dipping Sauce', category: 'sauce', price: 4.99, image: 'sauceimages/KikkomanTempuraDippingSauce.png', description: '500ml bottle' },
    { id: 157, name: 'Kikkoman Gluten Free Sweet Chilli Sauce', category: 'sauce', price: 5.49, image: 'sauceimages/KikkomanGlutenFreeSweetChilliSauce.png', description: '300ml bottle' },
    { id: 158, name: 'Lee Kum Kee Hoisin Sauce', category: 'sauce', price: 4.99, image: 'sauceimages/LeeKumKeeHoisinSauce.png', description: '300ml bottle' },
    { id: 159, name: 'Kamayan Sweet Shrimp Paste', category: 'fish-sauce', price: 4.49, image: 'sauceimages/KamayanSweetShrimpPaste.png', description: '250g jar' },
    { id: 160, name: 'Megachef Premium Mushroom Sauce', category: 'sauce', price: 5.49, image: 'sauceimages/MegachefPremiumMushroomSauce.png', description: '300ml bottle' },
    { id: 161, name: 'Silver Swan Coconut Vinegar', category: 'vinegar', price: 3.99, image: 'sauceimages/SilverSwanCoconutVinegar.png', description: '500ml bottle' },
    { id: 162, name: 'Kadoya 100% Pure Sesame Oil', category: 'oil', price: 6.99, image: 'sauceimages/Kadoya100%PureSesameOil.png', description: '500ml bottle' },
    { id: 163, name: 'J - Basket Teriyaki Sauce & Marinade Original', category: 'sauce', price: 4.99, image: 'sauceimages/J-BasketTeriyakiSauce&MarinadeOriginal.png', description: '300ml bottle' },
    { id: 164, name: 'Chin Su Fish Sauce', category: 'fish-sauce', price: 3.99, image: 'sauceimages/ChinSuFishSauce.png', description: '500ml bottle' },
    { id: 165, name: 'Pantai Sweet Soy Sauce', category: 'soy-sauce', price: 4.49, image: 'sauceimages/PantaiSweetSoySauce.png', description: '500ml bottle' },
    { id: 166, name: 'Lee Kum Kee Abalone Sauce', category: 'sauce', price: 5.99, image: 'sauceimages/LeeKumKeeAbaloneSauce.png', description: '300ml bottle' },
    { id: 167, name: 'Yamasa Sashimi Soy Sauce', category: 'soy-sauce', price: 5.99, image: 'sauceimages/YamasaSashimiSoySauce.png', description: '300ml bottle' },
    { id: 168, name: 'Anh Hong Mam Nem Pha San', category: 'fish-sauce', price: 4.49, image: 'sauceimages/AnhHongMamNemPhaSan.png', description: '500ml bottle' },
    { id: 169, name: 'Chin Su Soy Sauce Nuoc Tuong', category: 'soy-sauce', price: 3.99, image: 'sauceimages/ChinSuSoySauceNuocTuong.png', description: '500ml bottle' },
    { id: 170, name: 'Pantai Chicken Rice Sauce', category: 'sauce', price: 4.29, image: 'sauceimages/PantaiChickenRiceSauce.png', description: '250ml bottle' },
    { id: 171, name: 'Nong Phu Mam Nem Xay Fish Sauce', category: 'fish-sauce', price: 4.99, image: 'sauceimages/NongPhuMamNemXayFishSauce.png', description: '500ml bottle' },
    { id: 172, name: 'Wan Ja Shan Tamari Soy Sauce', category: 'soy-sauce', price: 5.49, image: 'sauceimages/WanJaShanTamariSoySauce.png', description: '500ml bottle' },
    { id: 173, name: 'Kikkoman Somen Tsuyu Sauce Base', category: 'sauce', price: 4.99, image: 'sauceimages/KikkomanSomenTsuyuSauceBase.png', description: '300ml bottle' },
    { id: 174, name: 'Kikkoman Gluten Free Soy Sauce', category: 'soy-sauce', price: 5.99, image: 'sauceimages/KikkomanGlutenFreeSoySauce.png', description: '500ml bottle' },
    { id: 175, name: 'Shinho Superfine Soy Sauce', category: 'soy-sauce', price: 4.29, image: 'sauceimages/ShinhoSuperfineSoySauce.png', description: '500ml bottle' },
    { id: 176, name: '40N Tin Fish Sauce', category: 'fish-sauce', price: 3.99, image: 'sauceimages/40NTinFishSauce.png', description: '500ml bottle' },
    { id: 177, name: 'Lee Kum Kee Original Stir-Fry Sauce', category: 'sauce', price: 4.79, image: 'sauceimages/LeeKumKeeOriginalStir-FrySauce.png', description: '300ml bottle' },
    { id: 178, name: 'Nong Phu Mam Nem Phu Quoc Fish Sauce', category: 'fish-sauce', price: 4.99, image: 'sauceimages/NongPhuMamNemPhuQuocFishSauce.png', description: '500ml bottle' },
    { id: 179, name: 'Kikkoman Sushi & Sashimi Soy Sauce', category: 'soy-sauce', price: 5.49, image: 'sauceimages/KikkomanSushi&SashimiSoySauce.png', description: '250ml bottle' },
    { id: 180, name: 'Haday Seafood Flavored Soy Sauce', category: 'soy-sauce', price: 4.99, image: 'sauceimages/HadaySeafoodFlavoredSoySauce.png', description: '500ml bottle' },
    { id: 181, name: 'Lee Kum Kee Black Bean Sauce', category: 'sauce', price: 4.49, image: 'sauceimages/LeeKumKeeBlackBeanSauce.png', description: '250ml bottle' },
    { id: 182, name: 'Mizkan Sesame Flavored Dressing', category: 'dressing', price: 3.99, image: 'sauceimages/MizkanSesameFlavoredDressing.png', description: '300ml bottle' },
    { id: 183, name: 'Longevity Peanut Oil Blend', category: 'oil', price: 5.49, image: 'sauceimages/LongevityPeanutOilBlend.png', description: '500ml bottle' },
    { id: 184, name: 'Lee Vietnamese Spring Roll Sauce', category: 'sauce', price: 3.99, image: 'sauceimages/LeeVietnameseSpringRollSauce.png', description: '250ml bottle' },
    { id: 185, name: 'Kikkoman Organic Soy Sauce', category: 'soy-sauce', price: 5.99, image: 'sauceimages/KikkomanOrganicSoySauce.png', description: '500ml bottle' },
    { id: 186, name: 'Sukina Teriyaki Sauce', category: 'sauce', price: 4.99, image: 'sauceimages/SukinaTeriyakiSauce.png', description: '250ml bottle' },
    { id: 187, name: 'Kikkoman Salad Rice Vinegar', category: 'vinegar', price: 4.29, image: 'sauceimages/KikkomanSaladRiceVinegar.png', description: '500ml bottle' },
    { id: 188, name: 'Lee Kum Kee Premium Old Oyster Saucer', category: 'sauce', price: 5.99, image: 'sauceimages/LeeKumKeePremiumOldOysterSaucer.png', description: '300ml bottle' },
    { id: 189, name: 'Nam Pla Oyster Fish Sauce', category: 'fish-sauce', price: 4.79, image: 'sauceimages/NamPlaOysterFIshSauce.png', description: '500ml bottle' },
    { id: 190, name: 'Kewpie Wafu Dressing', category: 'dressing', price: 4.49, image: 'sauceimages/KewpieWafuDressing.png', description: '300ml bottle' },
    { id: 191, name: 'Mam Nem Pha San Fish Sauce', category: 'fish-sauce', price: 4.29, image: 'sauceimages/MamNemPhaSanFishSauce.png', description: '500ml bottle' },
    { id: 192, name: 'Saigon Fish Sauce', category: 'fish-sauce', price: 3.99, image: 'sauceimages/SaigonFishSauce.png', description: '500ml bottle' },
    { id: 193, name: 'Datu Puti Sukang Sugarcane Vinegar', category: 'vinegar', price: 4.29, image: 'sauceimages/DatuPutiSukangSugarcaneVinegar.png', description: '500ml bottle' },
    { id: 194, name: 'Kikkoman Sweet & Sour Sauce', category: 'sauce', price: 4.99, image: 'sauceimages/KikkomanSweet&SourSauce.png', description: '300ml bottle' },
    { id: 195, name: 'J - Basket Creamy Miso Dressing', category: 'dressing', price: 4.49, image: 'sauceimages/J-BasketCreamyMisoDressing.png', description: '300ml bottle' },
    { id: 196, name: 'Wan Ja Shan Organic Gluten Free Tamari Soy Sauce', category: 'soy-sauce', price: 5.49, image: 'sauceimages/WanJaShanOrganicGlutenFreeTamariSoySauce.png', description: '500ml bottle' },
    { id: 197, name: 'Mizkan Jun Genmai Su Vinegar', category: 'vinegar', price: 4.29, image: 'sauceimages/MizkanJunGenmaiSuVinegar.png', description: '500ml bottle' },
    { id: 198, name: 'Kikkoman Black Bean Sauce with Garlic', category: 'sauce', price: 4.99, image: 'sauceimages/KikkomanBlackBeanSaucewithGarlic.png', description: '250ml bottle' },
    { id: 199, name: 'Con Gau Nuoc Tuong Soy Sauce', category: 'soy-sauce', price: 5.49, image: 'sauceimages/ConGauNuocTuongSoySauce.png', description: '500ml bottle' },
    { id: 200, name: 'Roxy Canola Olive Blended Oil', category: 'oil', price: 5.99, image: 'sauceimages/RoxyCanolaOliveBlendedOil.png', description: '500ml bottle' },
    { id: 201, name: 'Pearl River Superior Light Soy Sauce', category: 'soy-sauce', price: 5.49, image: 'sauceimages/PearlRiverSuperiorLightSoySauce.png', description: '500ml bottle' },
    { id: 202, name: 'Haday Signature Oyster Flavored Sauce', category: 'sauce', price: 5.99, image: 'sauceimages/HadaySignatureOysterFlavoredSauce.png', description: '500ml bottle' },
    { id: 203, name: 'Kikkoman Gluten Free Tamari Soy Sauce', category: 'soy-sauce', price: 5.99, image: 'sauceimages/KikkomanGlutenFreeTamariSoySauce.png', description: '500ml bottle' },
    { id: 204, name: 'Dynasty Chinese Duck Sauce', category: 'sauce', price: 4.79, image: 'sauceimages/DynastyChineseDuckSauce.png', description: '300ml bottle' },
    { id: 205, name: 'Red Boat Special Batch Fish Sauce', category: 'fish-sauce', price: 6.99, image: 'sauceimages/RedBoatSpecialBatchFishSauce.png', description: '500ml bottle' },
    { id: 206, name: 'Phu Quoc Fish Sauce', category: 'fish-sauce', price: 4.99, image: 'sauceimages/PhuQuocFishSauce.png', description: '500ml bottle' },
    { id: 207, name: 'Marukan Ponzu Premium Soy Dressing with Sudachi Citrus', category: 'sauce', price: 5.49, image: 'sauceimages/MarukanPonzuPremiumSoyDressingwithSudachiCitrus.png', description: '300ml bottle' },
    { id: 208, name: 'Marukan Lite Rice Vinegar', category: 'vinegar', price: 3.79, image: 'sauceimages/MarukanLiteRiceVinegar.png', description: '500ml bottle' },
    { id: 209, name: 'Haday Baizhuo Seasoning', category: 'seasoning', price: 4.99, image: 'sauceimages/HadayBaizhuoSeasoning.png', description: '250g jar' },
    { id: 210, name: 'Wan Ja Shan Organic Biologique Gluten Free Soy Sauce', category: 'soy-sauce', price: 6.49, image: 'sauceimages/WanJaShanOrganicBiologiqueGlutenFreeSoySauce.png', description: '500ml bottle' },
    { id: 211, name: 'Pantai Sweet Chili Sauce for Chicken', category: 'sauce', price: 4.49, image: 'sauceimages/PantaiSweetChiliSauceforChicken.png', description: '300ml bottle' },
    { id: 212, name: 'Datu Puti Toyomansi Soysauce with Calamansi', category: 'sauce', price: 4.29, image: 'sauceimages/DatuPutiToyomansiSoysaucewithCalamansi.png', description: '500ml bottle' },
    { id: 213, name: 'HanAsia Korean BBQ Sauce', category: 'sauce', price: 5.49, image: 'sauceimages/HanAsiaKoreanBBQSauce.png', description: '500ml bottle' },
    { id: 214, name: 'Kikkoman Double Fermented Prime Umami', category: 'sauce', price: 5.99, image: 'sauceimages/KikkomanDoubleFermentedPrimeUmami.png', description: '300ml bottle' },
    { id: 215, name: 'Assi Galbi Korean BBQ Sauce for Ribs', category: 'sauce', price: 6.49, image: 'sauceimages/AssiGalbiKoreanBBQSauceforRibs.png', description: '500ml bottle' }
];

// Function to display products with description and price
function displayProducts(productsToDisplay) {
    const productList = document.getElementById('product-list');
    productList.innerHTML = ''; // Clear previous products
    productsToDisplay.forEach(product => {
        const productDiv = document.createElement('div');
        productDiv.classList.add('product-item');
        productDiv.innerHTML = `
              <img src="${product.image}" alt="${product.name}">
            <h4>${product.name}</h4>
            <p class="price">$${product.price.toFixed(2)}</p>
            <p class="description">${product.description}</p>
            
        `;
        productList.appendChild(productDiv);
    });
}

// Initial display of all products
displayProducts(products);

// Price Label Update
function updatePriceLabel(value) {
    document.getElementById('price-label').textContent = `$${value}`;
}

// Filter Functionality
document.getElementById('price-range').addEventListener('input', function() {
    filterProducts();
});

document.getElementById('category-filter').addEventListener('change', function() {
    filterProducts();
});

// Filtering products by price and category
function filterProducts() {
    const priceLimit = parseFloat(document.getElementById('price-range').value);
    const selectedCategory = document.getElementById('category-filter').value;

    const filteredProducts = products.filter(product => {
        const priceMatch = product.price <= priceLimit;
        const categoryMatch = selectedCategory === 'all' || product.category === selectedCategory;
        return priceMatch && categoryMatch;
    });

    displayProducts(filteredProducts); // Display filtered products
}
